<?php require('../shared/header.phtml');?>

<!-- Content Start From Here -->
<div id="content_container"> 
  
  <!-- Liner Background Start From Here -->
  <div id="liner_bg_container">
    <div class="liner_bg">
      <div class="breadcrumb"><a href="index.php" title="Home">Home</a>> <a href="StudyDestinations.php" title="Study Detinations">Study Destinations</a>> <a href="../study_in_canada.html">Study in Canada</a>><span>List of institutions</span></div>
      <div class="img"><img src="../images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
    </div>
  </div>
  <!-- Liner Background End Here -->
  
  <div id="content"> 
    
    <!-- Left Content Start From Here -->
    <div id="lt_container">
      <h3 class="countryPage">My Options</h3>
      <!-- Content Start From Here -->
      <div class="vertMenu">
        <ul>
          <li><a href="student-visa-process.html" title="Student visa process"><span>4</span>Student visa process</a></li>
          <li><a href="list-of-institutions.html" title="List of institutions" class="active"><span>4</span>List of institutions</a></li>
          <li><a href="upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
          <li><a href="whats-new.html" title="What's new"><span>4</span>What's new</a></li>
          <li><a href="work-rights-for-students.html" title="Work rights during studies"><span>4</span>Work rights during studies</a></li>
          <li><a href="post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights</a></li>
          <li><a href="bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
          <li><a href="visitor-visa.html" title="Visitor visa"><span>4</span>Visitor visa</a></li>
        </ul>
      </div>
      <div class="gap20 fl"></div>
      <div class="innerContent">
        <h3>List of institutions</h3>
        <p>We are official representatives of many highly reputed institutions located in Canada. Our representation is spread across the various cities and education sectors including colleges, polytechnics and universities.</p>
        <div id="scrollbar1" style="width:410px; background:#f5f9fa">
          <div class="scrollbar">
            <div class="track">
              <div class="thumb">
                <div class="end"></div>
              </div>
            </div>
          </div>
          <div class="viewport" style="width:390px;height:385px;">
            <div class="overview">
              <ul class="whatsnew1">
                <!--<li>algonquin college</li>-->
				<li>arbutus college</li>
                <li>bow valley college</li>
                <li><a href="camosun-college-canada/index.html" target="_blank" title="Camosun College">camosun college</a></li>
                <li>college of the rockies</li>
                <li><a href="douglas-college/index.html" target="_blank" title="Douglas College">douglas college</a></li>
				<li>durham college</li>
                <li>fairleigh dickinson university</li>
                <li>fraser international college</li>
                <li><a href="georgian-college/index.html" target="_blank" title="Georgian College">georgian college</a></li>
                <li><a href="icm/index.html" target="_blank" title="International College of Manitoba">international college of manitoba</a></li>
                <!--<li><a href="kwantlen-polytechnic-university/index.html" target="_blank" title="Kwantlen Polytechnic University">kwantlen polytechnic university</a></li>-->
				<li>langara college</li>
				<li>le cordon bleu</li>
                <li>medicine hat college</li>
                <li><a href="sait-polytechnic/index.html" target="_blank" title="Sait Polytechnic">sait polytechnic</a></li>
				<li>selkirk college</li>
                <li>sheridan college</li>
                <li>st clair college</li>
				<li>st. lawrence college</li>
                <li>thompson rivers university</li>
                <li class="last"><a href="vancouver-community-college/index.html" target="_blank" title="Vancouver Community College">vancouver community college</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- Content End Here --> 
    </div>
    <!-- Left Content End Here --> 
    
    <!-- Right Content Start From Here -->
    <div id="rt_container">
      <div class="facts_container">
        <ul id="facts">
          <li><img src="../images/facts/canada/canada_1.jpg" width="300" height="105" alt="English and French are the official languages of Canada." /></li>
          <li><img src="../images/facts/canada/canada_2.jpg" width="300" height="105" alt="Maple leaf is in the center of Canada's flag." /></li>
          <li><img src="../images/facts/canada/canada_3.jpg" width="300" height="105" alt="Beaver is the national animal of Canada." /></li>
          <li><img src="../images/facts/canada/canada_4.jpg" width="300" height="105" alt="Canada has the world's highest tertiary education enrolment." /></li>
          <li><img src="../images/facts/canada/canada_5.jpg" width="300" height="105" alt="Canada has the ninth biggest economy of the world." /></li>
        </ul>
      </div>
      <!-- University Banner Script Start From Here -->
      <div style="overflow: hidden;"> 
        <!--<img src="../images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->
        <div style="border: none; margin-top: 15px;">
          <iframe src="../university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe>
        </div>
        <img src="../images/adv_banner_1.jpg" width="301" height="87" alt="Study visa consultants, Study in abroad" style="border: none; margin-top: 15px;" /> </div>
      <!-- University Banner Script End Here --> 
    </div>
    <!-- Right Content End Here --> 
    
  </div>
</div>
<!-- Content End Here --> 


<?php include_once '../shared/footer.phtml'; ?>                                                