<?php require('../shared/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">

	<!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="../index.html" title="Home">Home</a>> <a href="../study_destinations.html" title="Study Detinations">Study Destinations</a>> <a href="../study_in_canada.html">Study in Canada</a>><span>Student visa process</span></div>
            <div class="img"><img src="../images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
    
<div id="content">
	
    <!-- Left Content Start From Here -->
    <div id="lt_container">
    	<h3 class="countryPage">My Options</h3>
        <!-- Content Start From Here -->
    	<div class="vertMenu">
         
         <ul>
         <li><a href="student-visa-process.html" title="Student visa process" class="active"><span>4</span>Student visa process</a></li>
         <li><a href="list-of-institutions.html" title="List of institutions"><span>4</span>List of institutions</a></li>
         <li><a href="upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
         <li><a href="whats-new.html" title="What's new"><span>4</span>What's new</a></li>
         <li><a href="work-rights-for-students.html" title="Work rights for students"><span>4</span>Work rights for students</a></li>
         <li><a href="post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights</a></li>
         <li><a href="bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
         <li><a href="visitor-visa.html" title="Visitor visa"><span>4</span>Visitor visa</a></li>
         </ul>
        </div>
        <div class="gap20 fl"></div>
        <div class="innerContent">
        <h3>Student visa process</h3>        
        <div id="accordion">
            <h3><a href="#">Step 1: Attend a counselling session</a></h3>
            <div>
                <p>
                Attend a counseling session at your closest branch to find out your options relating to study destination, courses available and recommended institutions.
                </p>
            </div>
            <h3><a href="#">Step 2: Register with oceanic</a></h3>
            <div>
                <p>
                Register with Oceanic to start the admission and visa process.  We can help you navigate through the various processes and make studying overseas easier.  Remember, all our services are free of charge!
                </p>
            </div>
            <h3><a href="#">Step 3: Apply for admission</a></h3>
            <div>
                <p>Once you have decided what and where you want to study, we will help you complete the application to the institutions of your choice.  At the time of application for admission you will be required to submit several documents including proof of previous academic qualifications and in most cases proof of your English language ability. We will also provide you with a checklist for the documents you will need to provide when the time comes to apply for your visa (step 7).</p>
<p>By submitting your application through us you will be able to track the progress of your application as we send you automatic notifications of its progress.  We also take the hard work out of tracking the applications by keeping in contact with the institution on your behalf.</p>
            </div>
            <h3><a href="#">Step 4: Undertake medicals</a></h3>
            <div>
                <p>After submitting your application for admission, you will need to undertake a medical examination by one of the doctors approved by the Canadian Government.  A list of the approved panel doctors can be found by visiting: <br />
<a href="http://www.cic.gc.ca/dmp-md/medicalinfo.aspx?CountryID=1995&CountryName=India" target="_blank">http://www.cic.gc.ca/dmp-md/medicalinfo.aspx?CountryID=1995&CountryName=India </a>
You will be provided with a receipt (IMM1017) for the medicals, which you will need to submit at the time of lodging you visa application.  The medical report will automatically be sent to the visa office.
</p>
            </div>
            <h3><a href="#">Step 5: Organise funds</a></h3>
            <div>
                <p>Provide evidence of purchase of a special Guaranteed Investment Certificate (GIC) from a participating Canadian financial institution [currently it is only Scotia bank], for the amount of $10,000 CAD towards the first year living expenses and evidence of payment for of first year’s tuition fee OR </p>
<p>As an alternate option, students can meet the financial requirement by submitting a copy of the receipt for the first year’s tuition fee payment AND a copy of an educational Loan from an Indian Chartered Bank equivalent to $10,000 CAD.</p>

            </div>
            <h3><a href="#">Step 6: Pay tuition fee</a></h3>
            <div>
                <p>To accept your offer from an education provider, you must pay the tuition fee as advised by the institution.  You can choose to pay this fee through either Telegraphic Transfer (TT) or Direct Debit (DD).  Our value added services department at Oceanic Consultants can help you arrange either of these payment methods.</p>
<p>Once the institutions have received and processed your tuition fee payment, they will issue you with receipt.  This receipt will be needed to lodge your visa application.</p>
            </div>
            <h3><a href="#">Step 7: Visa lodgment</a></h3>
            <div>
                <p>In Canada, a student visa is known as a Study Permit.  To lodge your visa application you will need to provide the documents outlined in the checklist we provided you in step 3.  </p>
<p>Just like your admission application, Oceanic Consultants will keep you updated as to the progress of your application and take the hard work out of tracking your application by keeping in contact with the visa office on your behalf.</p>
            </div>
            <h3><a href="#">Step 8: Visa outcome</a></h3>
            <div>
                <p>We will notify you as soon as we know the outcome of your visa application so you can come in and collect your passport.  In most cases this is a positive response and it means you can also start planning your travel and accommodation for Canada!</p>
            </div>
            <h3><a href="#">Step 9: Travel services</a></h3>
            <div>
                <p>At Oceanic Consultants we can help you organise your travel arrangements to begin your new student life in Canada.  Air ticketing, insurance and foreign exchange can all be arranged through us to make studying overseas easier!</p>
            </div>
		</div>        
        
        </div>
        <!-- Content End Here -->
        
    </div>
    <!-- Left Content End Here -->
    
    <!-- Right Content Start From Here -->
	<div id="rt_container">
        <div class="facts_container">
        	<ul id="facts">
				<li><img src="../images/facts/canada/canada_1.jpg" width="300" height="105" alt="English and French are the official languages of Canada." /></li>
                <li><img src="../images/facts/canada/canada_2.jpg" width="300" height="105" alt="Maple leaf is in the center of Canada's flag." /></li>
                <li><img src="../images/facts/canada/canada_3.jpg" width="300" height="105" alt="Beaver is the national animal of Canada." /></li>
                <li><img src="../images/facts/canada/canada_4.jpg" width="300" height="105" alt="Canada has the world's highest tertiary education enrolment." /></li>
                <li><img src="../images/facts/canada/canada_5.jpg" width="300" height="105" alt="Canada has the ninth biggest economy of the world." /></li>
			</ul>        
        </div>
        <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="../images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->
        <div style="border: none; margin-top: 15px;"><iframe src="../university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
        <img src="../images/adv_banner_1.jpg" width="301" height="87" alt="Study visa consultants, Study in abroad" style="border: none; margin-top: 15px;" />
        </div>
        <!-- University Banner Script End Here -->
    </div>
    <!-- Right Content End Here -->
    
</div>
</div>
<!-- Content End Here -->

<?php include_once '../shared/footer.phtml'; ?>                                                