<!-- Banner Start From Here -->
    <div id="banner">
    	<div class="canadaBanner"><img src="images/study-in-NewZealand.png" alt="Study in New Zealand" usemap="#Map2" />
        <map name="Map2" id="Map2">
            <area shape="poly" coords="421,164,436,147,462,139,490,138,524,147,535,164,524,179,482,191,438,183" href="Register.php" target="_self" title="Register Now" />
        </map>
        </div>
        <!-- Search Box Start From Here -->
        <div id="search_box_container">
        	<!--<div id="search_box">
            	<input type="text" name="txt_uname" id="txt_uname" class="txt_box" value="Search" style="float:left; padding: 4px 4px; margin: 0x 2px; width: 119px;" /><input type="image" name="btn_submit_search" id="btn_submit_search" src="images/btn_go.jpg" />
            </div>-->
            <div id="country_selection_box">
            	<select name="dd_countries" id="dd_countries" class="txt_box" style="float:left; padding: 4px 4px; width: 145px; margin: 0px 2px;">
                	<option value="">--Select Country--</option>
                    <option value="study_in_australia.html">Australia</option>
                    <option value="study_in_canada.html">Canada</option>
                    <option value="study_in_newzealand.html">New Zealand</option>
                    <option value="study_in_the_uk.html">UK</option>
                    <option value="study_in_the_usa.html">USA</option>
                </select>
            </div>
        </div>
        <!-- Search Box End Here -->
        
  </div>
    <!-- Banner End Here -->