<!-- Banner Start From Here -->
<div id="banner">
    <div class="model"><img src="images/study_in_abroad.png" width="269" height="431" align="right" alt="Study in abroad"></div>

    <!-- Banner Backgrounds Start From Here -->
    <div class="banner_countries">
        <img src="images/header_contries_bg.png" alt="" width="720" height="230" border="0" usemap="#studies_locations">
        <map name="studies_locations" id="studies_locations">
            <area shape="rect" coords="36,129,85,183" href="StudyInCanada.php" title="Study in Canada" alt="Study in Canada">
            <area shape="poly" coords="169,116,169,228,247,228" href="StudyInTheUSA.php" title="Study in the USA" alt="Study in the USA">
            <area shape="rect" coords="276,70,312,165" href="StudyInTheUk.php" title="Study in the UK" alt="Study in the UK">
            <area shape="poly" coords="382,151,418,178,438,172,468,176,455,187,492,185,490,219,331,219,322,197,336,177,366,159" href="StudyInAustralia.php.html" title="Study in Australia" alt="Study in Australia">
            <area shape="poly" coords="615,99,632,99,651,101,676,110,687,118,689,135,666,152,645,155,628,157,606,154,587,146,572,133,577,118,590,106" href="Register.php" title="Register Now" alt="Register Now">
            <area shape="poly" coords="673,155,699,162,708,169,708,182,699,190,681,195,668,198,644,191,633,179,637,166,650,159" href="Contact.php" title="Find Us" alt="Find Us">
            <area shape="poly" coords="516,205,529,186,550,184,574,167,594,138,588,160,588,185,591,209,580,227,531,225" href="StudyInNewZealand.php" title="Study in New Zealand">
        </map>
    </div>

    <div class="banner_slogan_container">
        <div class="banner_slogan" style="display: block;">

            <div id="testimonials2">
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body">
                            <p>that we have placed more than 10,000 students at various institutions overseas?</p>
                        </div>
                    </div>                              
                </blockquote>
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body">
                            <p>that we have one of the largest company owned offices in India?</p>
                        </div>
                    </div>                              
                </blockquote>
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body">
                            <p>that we take care of everything from admission to visa to air-ticketing?</p>
                        </div>
                    </div>                              
                </blockquote>
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body">
                            <p>that we have one of the highest visa success rates in the industry?</p>
                        </div>
                    </div>                              
                </blockquote> 
            </div>
        </div>
    </div>
    <!-- Banner Background End Here -->        


</div>
<!-- Banner End Here -->
