<!-- Banner Start From Here -->
<div id="banner">
    <div class="canadaBanner"><img src="images/study-in-canada.png" alt="Study in canada" border="0" usemap="#Map2" />
        <map name="Map2" id="Map2">
            <area shape="poly" coords="348,162,363,145,389,137,417,136,451,145,462,162,451,177,409,189,365,181" href="Register.php" target="_self" title="Register Now" />
        </map>
    </div>
</div>
<!-- Banner End Here -->
