<!-- Banner Start From Here -->
<div id="banner">
    <div class="canadaBanner"><img src="images/study-in-UK.png" alt="Study in the UK" usemap="#Map2" />
        <map name="Map2" id="Map2">
            <area shape="poly" coords="300,151,315,134,341,126,369,125,403,134,414,151,403,166,361,178,317,170" href="Register.php" target="_self" title="Register Now" />
        </map>
    </div>
</div>
<!-- Banner End Here -->