<!-- Banner Start From Here -->
<div id="banner">
    <div class="canadaBanner"><img src="images/study-in-NewZealand.png" alt="Study in New Zealand" usemap="#Map2" />
        <map name="Map2" id="Map2">
            <area shape="poly" coords="421,164,436,147,462,139,490,138,524,147,535,164,524,179,482,191,438,183" href="Register.php" target="_self" title="Register Now" />
        </map>
    </div>
</div>
<!-- Banner End Here -->