<!-- Banner Start From Here -->
<div id="banner">
    <div class="canadaBanner"><img src="images/study-in-australia.png" alt="Study in australia" usemap="#Map2" />
        <map name="Map2" id="Map2">
            <area shape="poly" coords="433,173,448,156,474,148,502,147,536,156,547,173,536,188,494,200,450,192" href="Register.php" target="_self" title="Register Now" />
        </map>
    </div>
</div>
<!-- Banner End Here -->