<!-- Banner Start From Here -->
<div id="banner">
    <div class="canadaBanner"><img src="images/study-in-USA.png" alt="Study in the USA" usemap="#Map2" />
        <map name="Map2" id="Map2">
            <area shape="poly" coords="374,168,389,151,415,143,443,142,477,151,488,168,477,183,435,195,391,187" href="Register.php" target="_self" title="Register Now" />
        </map>
    </div>
</div>
<!-- Banner End Here -->