<div style="margin-bottom: 15px;"><img src="images/study_destinations.jpg" alt="Study Destinations" width="301" height="217" border="0" usemap="#Map2">
            <map name="Map2" id="Map2">
            <area shape="rect" coords="145,181,280,198" href="StudyInTheUSA.php" title="Study in the USA">
            <area shape="rect" coords="145,149,275,166" href="StudyInTheUk.php" title="Study in the UK">
            <area shape="rect" coords="145,117,247,134" href="StudyInNewZealand.php" title="Study in New Zealand">
            <area shape="rect" coords="145,85,280,102" href="StudyInCanada.php" title="Study in Canada">
            <area shape="rect" coords="145,54,280,71" href="StudyInTheAustralia.php" title="Study in Australia">
            </map>
</div>