<!-- Footer Start From Here -->
<div id="footer">
	<div id="footer_container">
    
    	<!-- Footer Left Start From Here -->
    	<div class="lt">
        	<div class="lnk_container">
            <ul style="margin-top: 10px;">
            <li><a href="#" title="Sitemap">Sitemap</a></li>
            <li><a href="index.php" title="Home">Home</a></li>
            <li><a href="AboutUs.php" title="About Us">About Us</a></li>
            <li><a href="Services.php" title="Services">Services</a></li>
            <li><a href="Events.php" title="Events">Events</a></li>
            <li><a href="Contact.php" title="Contact Us">Contact Us</a></li>
            </ul>
            </div>
            
            <div class="lnk_container" style="margin: 0px 20px 0px -20px;">
            <h3><a href="StudyInTheUk.php" title="Study Destinations">Study Destinations</a></h3>
            <ul>
            <li><a href="StudyInAustralia.php" title="Study in Australia"><img src="images/aus_flag.jpg" width="18" height="11" alt="Australia" border="0">&nbsp;&nbsp;Study in Australia</a></li>
            <li><a href="StudyInCanada.php" title="Study in Canada"><img src="images/canada_flag.jpg" width="18" height="11" alt="Canada" border="0">&nbsp;&nbsp;Study in Canada</a></li>
            <li><a href="StudyInNewZealand.php" title="Study in New Zealand"><img src="images/new_zeland_flag.jpg" width="18" height="11" alt="New Zealand" border="0">&nbsp;&nbsp;Study in New Zealand</a></li>
            <li><a href="StudyInTheUk.php" title="Study in the UK"><img src="images/uk_flag.jpg" width="18" height="11" alt="United Kindom" border="0">&nbsp;&nbsp;Study in the UK</a></li>
            <li><a href="StudyInTheUSA.php" title="Study in the USA"><img src="images/us_flag.jpg" width="18" height="11" alt="USA" border="0">&nbsp;&nbsp;Study in the USA</a></li>
            </ul>
            </div>
            
            <div class="lnk_container">
            <h3><a href="NewsRoom.php" title="Newsroom">Newsroom</a></h3>
            <!--<ul>            
            <li><a href="news_room.html" title="What's New">- What's New</a></li>
            <li><a href="in_press.html" title="Oceanic In Press">- Oceanic In Press</a></li>
            </ul>-->
            </div>
            
            <div class="lnk_container">
            <h3><a href="WorkWithUs.php" title="Work with us">Work with us</a></h3>
            <ul>
            <li><a href="Careers.php" title="Career with Oceanic">- Career with Oceanic</a></li>
            <li><a href="Patner.php" title="Partner with Oceanic">- Partner with Oceanic</a></li>
            </ul>
            </div>            
        </div>
        <!-- Footer Left End Here -->
        
        <!-- Footer Right Start From Here -->
        <div class="rt">
            <div class="lnk_container">            
            <h3>Follow us on:</h3>
            <img src="images/social_websites_icons.jpg" alt="" width="28" height="28" border="0" usemap="#Map">
            <map name="Map" id="Map">
                <area shape="rect" coords="2,1,28,26" href="http://www.youtube.com/ocagroup" target="_blank" title="Find us on Youtube" alt="Youtube">
            </map>

            <!-- Facebook Recommend Button -->
            <div style="position:absolute; top:31px; left:34px;">
                <div id="fb-root" class=" fb_reset"><div style="position: absolute; top: -10000px; height: 0px; width: 0px;"><div><iframe name="fb_xdm_frame_http" frameborder="0" allowtransparency="true" scrolling="no" id="fb_xdm_frame_http" aria-hidden="true" title="Facebook Cross Domain Communication Frame" tab-index="-1" src="images/xd_arbiter.htm" style="border: none;"></iframe><iframe name="fb_xdm_frame_https" frameborder="0" allowtransparency="true" scrolling="no" id="fb_xdm_frame_https" aria-hidden="true" title="Facebook Cross Domain Communication Frame" tab-index="-1" src="images/xd_arbiter(1).htm" style="border: none;"></iframe></div></div><div style="position: absolute; top: -10000px; height: 0px; width: 0px;"><div></div></div></div>
                <script>                    (function (d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s); js.id = id;
                        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                        fjs.parentNode.insertBefore(js, fjs);
                    } (document, 'script', 'facebook-jssdk'));
                </script>
                <div class="fb-like fb_edge_widget_with_comment fb_iframe_widget" data-href="http://www.oceanicconsultants.com" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" data-font="arial" fb-xfbml-state="rendered"><span style="height: 20px; width: 81px;"><iframe id="f3598e7fa4" name="f6b5ed904" scrolling="no" title="Like this content on Facebook." class="fb_ltr" src="images/like.htm" style="border: none; overflow: hidden; height: 20px; width: 81px;"></iframe></span></div>
            </div>
            <!-- Facebook Recommend Button -->

            </div>
        </div>
        <!-- Footer Right End Here -->
    </div>    
    <div id="footer_btm">
    	<div id="footer_btm_container">
        	<p align="right">© 2013, International Student Recruitment Agency. all rights reserved. | <a href="http://www.oceanicconsultants.com/privacy_policy.html" title="Privacy Policy">privacy policy</a></p>
        </div>
    </div>
</div>
<!-- Footer End Here -->

<script type="text/javascript">
window.openRegister = function (url,caption) {
    postToUrl(url, { cid: "0", ids: "0" });
}
</script>
<script type="text/javascript">
function showform(){
//    var url = "registerwithus.aspx?instituteid=&keepThis=true&TB_iframe=true&height=550&width=575";
    var url = "registration.aspx?instituteid=&keepThis=true&TB_iframe=true&height=550&width=575";
	var url = "registerwithus.aspx";

   tb_show("", url, false);
   $("#TB_overlay").unbind();
}
</script>


</body></html>