<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0047)http://www.oceanicconsultants.com/services.html -->
<html xmlns="http://www.w3.org/1999/xhtml" class="cufon-active cufon-ready"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8">
<meta name="Keywords" content="overseas education, study overseas, Study in overseas, Study in Australia, Study in the UK, why to Study in abroad, visa to Study in uk, study overseas visa">
<meta name="Description" content="Oceanic Consultants: Helps you with course selection, getting admission in professional courses, student visa and travel arrangements. We help students who are looking for studying abroad like Study in USA, Study in Australia, Study in UK, Study in Canada and Study in New Zealand.">
<title>Abroad Oceanic Consultants: study visa in Australia | Education Consultants services India</title>
<link href="css/home.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="css/ddsmoothmenu.css">
<link rel="stylesheet" type="text/css" href="css/common.css">

<script id="facebook-jssdk" src="js/all.js"></script>
<script type="text/javascript" async="" src="js/ga.js"></script>
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/ddsmoothmenu.js"></script>

<script type="text/javascript" src="js/jquery-latest.pack.js"></script>
<script type="text/javascript" src="js/jcarousellite_1.0.1.js"></script>
<script type="text/javascript" src="js/jquery.innerfade.js"></script>

<script type="text/javascript" src="js/common.js"></script>

<script type="text/javascript" src="js/oceanic.js"></script>
  <!-- include Cycle plugin -->
<script type="text/javascript" src="https://filemasbayu.googlecode.com/files/jquery.cycle.all.latest.js"></script>

 <script type="text/javascript">
                                        $(document).ready(function() {
                                            $('#testimonials1')
                                                    .after('<div id="nav2">')
                                                    .cycle({
                                                fx: 'fade', // choose your transition type, ex: fade, scrollUp, scrollRight, shuffle
                                                //pager:  '#nav2'              
                                            });
                                            $('#testimonials1').css('height', '40px');


                                            $('#testimonials2')
                                                    .after('<div id="nav2">')
                                                    .cycle({
                                                fx: 'fade', // choose your transition type, ex: fade, scrollUp, scrollRight, shuffle
                                                //pager:  '#nav2'

                                            });
                                        });
                                    </script>   
    
</head>
<body>

<!-- Header Start From Here -->
<div id="header">
	
<?php require('Views/menu.phtml');?>
<?php require('Views/banner_'.$view->bannerTitle.'.phtml');?>  

</div>
<!-- Header End Here -->