<!-- Testimonials Start From Here -->
<div id="testimoni_container">
    <div class="testi_container">
        <div class="testi" style="display: block;">
            <div class="new-sidebar-blurb customer-speaks">
    <h2>Hear from our Students...</h2>
     <div id="testimonials1" >
         <blockquote>
            <img src="images/testimonials/sunkari.jpg" class="customer-speaks-img" style="width:47px;height:57px">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
               ISRA provided me with excellent services giving apt and practical advice/guidance at every stage of my application process.
                 <cite>&ndash;Srinivas Sunkari, University Of Salford, UK</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
    </blockquote>
          <blockquote>
            <img src="images/testimonials/goutham.jpg" class="customer-speaks-img" style="width:47px;height:57px">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
              My experience with ISRA was phenomenal. Special thanks to Thirumalesh Sunkari, Pallavi ma’am for helping me with everything. In two months ISRA helped me to get admission into Ohklama State University something I wouldn’t ever be capable of.
                 <cite>&ndash;Goutham Naik, OHK, US</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
        </blockquote>
         <blockquote>
            <img src="images/testimonials/ankush.jpg" class="customer-speaks-img" style="width:47px;height:57px">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
               I really think that you guys are the best counsellors out there. There is no one who I would not recommend ISRA to.
                 <cite>&ndash;Ankush Veer Reddy, Texas A&amp;M, US</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
        </blockquote>
          <blockquote>
            <img src="images/testimonials/kandadi.jpg" class="customer-speaks-img" style="width:47px;height:57px">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
              I have had a great experience working with ISRA during my application process to the UK. I find the staff extremely approachable and helpful. They have also been very prompt and efficient in answering my queries and clearing numerous doubts!  
              <cite>&ndash;Vamshi Kandadi, Salford University, UK</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
        </blockquote>
          <blockquote>
            <img src="images/testimonials/munugala.jpg" class="customer-speaks-img" style="width:47px;height:57px">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
             Everything was taken care of at ISRA. Assistance was given at every step. Personal attention given and I would definitely come back and suggest others
             <cite>&ndash;Munugala Harish, Salford University, UK</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
        </blockquote>
         <blockquote>
            <img src="images/testimonials/rambha.jpg" class="customer-speaks-img" style="width:47px;height:57px">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
           I owe all of my future to ISRA and hope that you keep helping students achieve their dreams in future. A very big thank you to the ISRA team – without you I would have no college to go to.  
           <cite>&ndash;Srinivas Ramba, Middlesex University, UK</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
        </blockquote>
         <blockquote>
            <img src="images/testimonials/annamreddy.jpg" class="customer-speaks-img" style="width:47px;height:57px">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
         My experience throughout from the counseling through the results went very smoothly without any problems. The staff also was very cordial. I would definitely recommend your services to others. Thank you once again.
         <cite>&ndash;Ravikiran AnnamReddy, Salford university, UK</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
        </blockquote>
     </div>
      </div>
    </div><!--end .testimonials2-->
</div>
</div>

<!-- Testimonials End Here -->
