 <!-- Testimonials Start From Here -->
     <div id="testimoni_container">
    	<div class="testi_container">
             <div class="testi" style="display: block;">
         
    <h2>Testimonials</h2>
<div id="testimonials1" >

 <blockquote ><p>"At first, I was extremely nervous about going abroad. I’ve always been a bit of a control-freak and I knew that while studying abroad in The Netherlands and traveling throughout Europe there would be so much out of my control. But, it was such an important opportunity for me to get out of my comfort zone. It put many things from my life in the States in perspective for me—relationships, careers, friendships. When I was abroad, I learned to go-with-the-flow more, which has truly made my post-abroad life easier. If you worry too much, you’ll miss out on the amazing sights and experiences. I’ve taken that mentality back home with me and it truly is the best souvenir."
                <cite>&ndash;Harish - Netherlands</cite></p></blockquote>
 
                <blockquote><p>"I would like to recommend Thirumalesh as an extremely supportive person who help to any kind of process to study in the UK. Gerard has the skills and the experience to solve any problem related with the UK university processes.

I have the experience of the aforementioned because I did masters in RF at University of Leeds and nowdays, I am in the third year of my PhD in telecomms."
                <cite>&ndash;Kranthi - UK</cite></p></blockquote>
 
                <blockquote><p>"Hello Sir,

This is Vijay here, .Just writing you to thank you for the help and guidance with everything that got me at this point.Will come to meet you when I make a visit to India in Jan-Feb. 

Give my regards to the staff at office. Thanks."
                <cite>&ndash;Vijay - Sheffield</cite></p></blockquote>
</div>
</div><!--end .testimonials2-->
        </div>
     </div>
  
    <!-- Testimonials End Here -->
    