<!-- Testimonials Start From Here -->
<div id="testimoni_container">
    <div class="testi_container">
        <div class="testi" style="display: block;">
            <div class="new-sidebar-blurb customer-speaks">
    <h2>Hear from our Students...</h2>
     <div id="testimonials1" >
         <blockquote>
            <img src="images/c-anwar-hussain.jpg" class="customer-speaks-img">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
               "Hello Sir,

                    This is Vijay here, .Just writing you to thank you for the help and guidance with everything that got me at this point.Will come to meet you when I make a visit to India in Jan-Feb. 

                    Give my regards to the staff at office. Thanks."
                 <cite>&ndash;Vijay, Sheffield</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
    </blockquote>
          <blockquote>
            <img src="images/c-anwar-hussain.jpg" class="customer-speaks-img">
            <div class="customer-speaks-wrp">
                <div class="customer-speaks-blurb">
                    <div class="icon-top"></div>
               "Hello Sir,

                    This is Vijay here, .Just writing you to thank you for the help and guidance with everything that got me at this point.Will come to meet you when I make a visit to India in Jan-Feb. 

                    Give my regards to the staff at office. Thanks."
                 <cite>&ndash;Vijay, Sheffield</cite>
                <img src ="images/icon-quote-bottom.gif" alt="icon-quote-bottom"/>                
                </div>             
            </div>
                    </blockquote>
     </div>
      </div>

         
    </div><!--end .testimonials2-->
</div>
</div>

<!-- Testimonials End Here -->
