<?php require('Views/header.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>About Us</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">About Us</h3>
                
                <div style="overflow: hidden;">
                    ISRA Consultants, established in 2005, is one of the most successful international student recruitment companies in the world today. The company, with its head office in Hyderabad, India has one of the largest networks of company owned offices in India.
                    <br /><br />
                    We help thousands of students every year to pursue higher education overseas. Motivated by our core values ‘ethics, expertise and leadership’, we are one of the most trusted names in the field of overseas education.
                    <br /><br />
                    We offer students a choice of thousands of courses at various leading educational institutions in Australia, Canada, New Zealand, United Kingdom and United States of America. With more than 9 years of experience, world class infrastructure and state of art technology, you can expect the best from us. <a href="contact.php" title="Visit our nearest office. today.">Visit our nearest office today.</a>
                </div>
                
                <div style="overflow: hidden;">
                    <br /><br />
                    <div class="lt_box">
                        <h3 class="heading_small">Our Mission</h3>
                        We are committed to our customer centric philosophy. Our mission is to help our clients achieve their goals by providing them world class customer service that is both reliable and competitively superior.
                    </div>
                    <div class="rt_box">
                        <h3 class="heading_small">Our Vision</h3>
                        To be the global leader in the field of international student recruitment.
                    </div>
                </div>
                
                <div style="overflow: hidden;">
                    <br /><br />
                    <div class="lt_box">
                        <h3 class="heading_small">Our Values</h3>
                        We are driven by our core values ‘ethics, expertise and leadership’. We believe that honesty paves the way for true success. in sync with our values, we strongly discourage students to use any fraudulent means for pursuing their studies overseas.
                    </div>
                    <div class="rt_box">
                        <h3 class="heading_small">Why Us</h3>
                        It's quite simple; we charge the institutions overseas for our services. Being an ethical operator, we do not have the policy of double charging i.e. charging the institutions overseas as well as charging you. We only bill the institutions for our services thus saving you significant amount of money that you would incur otherwise.
                    </div>
                </div> 
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">
              <?php require 'Views/destinations_carousel.phtml';?>
            
         <!--   <div class="credentials">        	
                <a href="#" class="prev"></a>
                <div class="credential_scoller">            
                <div class="jCarouselLite">
                    <ul>
                        <li><img src="images/airc_logo.png" alt="American International Recruitment Council" /></li>
                        <li><img src="images/evisa_logo.png" alt="eVisa" /></li>              
                        <li><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent" /></li>                        
                        <li><img src="images/aaeri_logo.png" alt="Education In Australia" /></li>
                        <li><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010" /></li>                                    
                        <li><img src="images/brw_award.png" alt="BRW Fast 100 Award" /></li>
                        <li><img src="images/coco_logo.png" alt="Company Owned Company Operated" /></li>
                    </ul>
                </div>
                </div>
                <a href="#" class="next"></a>
            </div> -->
            
            <!-- University Banner Script Start From Here -->
          
                <?php require 'Views/twitter_feed.phtml'?>                 
     
                  <!-- University Banner Script End Here -->  
        </div>
        <!-- Right Content End Here -->        
   
    
</div>
<!-- Content End Here -->
<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='About Us']").addClass('active');                                                   
     });
 </script>

<?php include_once 'Views/footer.phtml'; ?>                                                