<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>> <a href="WorkWithUs.php" title="Work With Us">Work With Us</a>><span>Careers</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Careers</h3>
                
                <div style="overflow: hidden;">
                    Want to become a key team member with one of the world leaders in overseas education? Would you like to have the chance to contribute as part of a team that is making dreams become a reality for clients? Then you should explore a career with oceanic consultants. 
                    <br /><br />
                    We have been able to achieve tremendous results with an outstanding team of professionals all focused on a shared and powerful vision. We could not have achieved this level of excellence without the contribution of more than 200 employees in India and Australia.
                    <br /><br />
                    <span class="heading">Work with oceanic consultants</span>
                    <br />
                    We're looking for bright, enthusiastic, self-starting people who want to work in an exciting, fast-paced environment using the latest technology and products. If you fit the job description, or have a good customer service background and are looking for an exciting career opportunity with a rapidly expanding service oriented company. <a class="thickbox" href="#">click here</a> to view current job opportunities.
                    <br /><br />
                    <span class="heading">To Apply</span>
                    <br />
                    If you feel you have what it takes to join this dynamic team please apply as soon as possible via email. To apply please email your resume in Word or PDF format to t.sunkari@gmail.com the subject line must read the position title.
                </div>               
                                           
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">            
            <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="#" class="prev"></a>
                <div class="credential_scoller">            
                <div class="jCarouselLite">
                    <ul>
                        <li><img src="images/airc_logo.png" alt="American International Recruitment Council"></li>
                        <li><img src="images/evisa_logo.png" alt="eVisa"></li>              
                        <li><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li>                        
                        <li><img src="images/aaeri_logo.png" alt="Education In Australia"></li>
                        <li><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li>                                    
                        <li><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li>
                        <li><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                    </ul>
                </div>
                </div>
                <a href="#" class="next"></a>
            </div>
            
            <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
		<img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
        </div>
        <!-- University Banner Script End Here -->
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->
<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='Work With Us']").addClass('active');                                                   
     });
 </script>

<?php include_once 'Views/footer.phtml'; ?>                                                