<?php require('Views/header_'.$view->headerTitle.'.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
      <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>><span>Contact Us</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
          <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Contact Us</h3>
                
                <div style="overflow: hidden;">
                    <!--<iframe id="frmMap" src="LocationMap/Default.aspx" style="width:100%; height:550px;" frameborder="0"></iframe>-->
                    <div style="overflow: hidden;">                    
                    <h3 style="font-size: 13px;">India</h3>
                    ISRA-International Student Recruitment Agency Pvt.Ltd<br />
                    Flat no.101, First floor, Swarga Nivas Enclave,<br />
                    Near Prime Hospitals, Ameerpet, Hyderabad-38<br /><br />
                    Tel: +91 8686286000/ +91 9849598792<br />
                    Email: t.sunkari@gmail.com<br /><br />                    
                    </div>
                  
                </div>
                      
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">
            <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="http://www.oceanicconsultants.com/services.html#" class="prev"></a>
                <div class="credential_scoller" style="visibility: visible; overflow: hidden; position: relative; z-index: 2; left: 0px;">            
                <div class="jCarouselLite">
                    <ul style="margin: 0px; padding: 0px; position: relative; list-style-type: none; z-index: 1; width: 1014px; left: -234px;"><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li>              
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li>                        
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aaeri_logo.png" alt="Education In Australia"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li>                                    
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li></ul>
                </div>
                </div>
                <a href="http://www.oceanicconsultants.com/services.html#" class="next"></a>
            </div>            
            
            <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="images/university_banners.htm" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
		<img src="http://www.oceanicconsultants.com/images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;">
        </div>
        <!-- University Banner Script End Here -->
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->

<?php include_once 'Views/footer.phtml'; ?>                                                