<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyBjhym1AzMFlYsvCyLW7bKeShaWzdtLC7Y&sensor=false"></script>

<div id="content_container">
	
      <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>Contact Us</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
          <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Contact Us</h3>
                
                <div style="overflow: hidden;">
                    <div style="overflow: hidden;">                    
                    <h3 style="font-size: 13px;">India</h3>
                    International Student Recruitment Agency Pvt. Ltd<br />
                    Flat no.101, First floor, Swarga Nivas Enclave,<br />
                    Near Prime Hospitals, Ameerpet, Hyderabad-38<br /><br />
                    Tel: +91 8686286000/ +91 9849598792<br />
                    Email: enquiries@international-student.in<br /><br />                    
                    </div>
                  
                </div>
             <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=swarga+nivas+apartment,+ameerpet&amp;aq=&amp;sll=17.441688,78.414984&amp;sspn=0.09777,0.154324&amp;ie=UTF8&amp;hq=&amp;hnear=Swarga+Niwas,+Meghamala+Apartment+Rd,+Srinivasa+Nagar,+Ameerpet,+Hyderabad,+Andhra+Pradesh+500082,+India&amp;t=m&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=swarga+nivas+apartment,+ameerpet&amp;aq=&amp;sll=17.441688,78.414984&amp;sspn=0.09777,0.154324&amp;ie=UTF8&amp;hq=&amp;hnear=Swarga+Niwas,+Meghamala+Apartment+Rd,+Srinivasa+Nagar,+Ameerpet,+Hyderabad,+Andhra+Pradesh+500082,+India&amp;t=m&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>     
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">
            <?php require 'Views/destinations_carousel.phtml';?>
            <?php require 'Views/twitter_feed.phtml'?>    
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->
<script>
    function initialize() {
  var myLatlng = new google.maps.LatLng(-25.363882,131.044922);
  var mapOptions = {
    zoom: 4,
    center: myLatlng
  }
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'International Student Recuitment Agency!'
  });
}
     $(document).ready(function() {
        $("#map-canvas").on("load", function () {
       initialize();            
    });                                                 
     });
     
    </script>

<?php include_once 'Views/footer.phtml'; ?>                                                