<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyBjhym1AzMFlYsvCyLW7bKeShaWzdtLC7Y&sensor=false"></script>

<div id="content_container">
	
      <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>><span>Contact Us</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
          <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Contact Us</h3>
                
                <div style="overflow: hidden;">
                    <div style="overflow: hidden;">                    
                    <h3 style="font-size: 13px;">India</h3>
                    ISRA-International Student Recruitment Agency Pvt.Ltd<br />
                    Flat no.101, First floor, Swarga Nivas Enclave,<br />
                    Near Prime Hospitals, Ameerpet, Hyderabad-38<br /><br />
                    Tel: +91 8686286000/ +91 9849598792<br />
                    Email: t.sunkari@gmail.com<br /><br />                    
                    </div>
                  
                </div>
             <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=swarga+nivas+apartment,+ameerpet&amp;aq=&amp;sll=17.441688,78.414984&amp;sspn=0.09777,0.154324&amp;ie=UTF8&amp;hq=&amp;hnear=Swarga+Niwas,+Meghamala+Apartment+Rd,+Srinivasa+Nagar,+Ameerpet,+Hyderabad,+Andhra+Pradesh+500082,+India&amp;t=m&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=swarga+nivas+apartment,+ameerpet&amp;aq=&amp;sll=17.441688,78.414984&amp;sspn=0.09777,0.154324&amp;ie=UTF8&amp;hq=&amp;hnear=Swarga+Niwas,+Meghamala+Apartment+Rd,+Srinivasa+Nagar,+Ameerpet,+Hyderabad,+Andhra+Pradesh+500082,+India&amp;t=m&amp;z=14&amp;iwloc=A" style="color:#0000FF;text-align:left">View Larger Map</a></small>     
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">
            <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="http://www.oceanicconsultants.com/services.html#" class="prev"></a>
                <div class="credential_scoller" style="visibility: visible; overflow: hidden; position: relative; z-index: 2; left: 0px;">            
                <div class="jCarouselLite">
                    <ul style="margin: 0px; padding: 0px; position: relative; list-style-type: none; z-index: 1; width: 1014px; left: -234px;"><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li>              
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li>                        
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aaeri_logo.png" alt="Education In Australia"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li>                                    
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li></ul>
                </div>
                </div>
                <a href="http://www.oceanicconsultants.com/services.html#" class="next"></a>
            </div>            
            
            <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="images/university_banners.htm" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
		<img src="http://www.oceanicconsultants.com/images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;">
        </div>
        <!-- University Banner Script End Here -->
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->
<script>
    function initialize() {
  var myLatlng = new google.maps.LatLng(-25.363882,131.044922);
  var mapOptions = {
    zoom: 4,
    center: myLatlng
  }
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'International Student Recuitment Agency!'
  });
}
     $(document).ready(function() {
        $("#map-canvas").on("load", function () {
       initialize();            
    });                                                 
     });
     
    </script>

<?php include_once 'Views/footer.phtml'; ?>                                                