<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>><span>Upcoming Admission Interviews</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Upcoming Admission Interviews</h3>
                Here is your opportunity to meet with the officials from overseas institutions directly. To enroll for an interview session, please select our branch closest to you:<br /><br />
                <div id="divSels" style="display:none;">
                <div class="state fl" style="width: 230px; margin-right: 10px;">
                    <label>State</label>
                    <div class="frm_txt_box_container">
                        <select id="selState" class="txt_box"></select>
                    </div>
                </div>
                <div style="width: 20px; float: left;">&nbsp;</div>
                <div class="city fl" style="width: 230px;">
                    <label>City</label>
                    <div class="frm_txt_box_container">
                    <select id="selCity" class="txt_box"></select>
                    </div>
                </div>
                    <div id="errorDiv" style="color:Red; display:none;">No data found</div>
                <div style="clear:both;" id="addressContainer" class="address_box"></div>
                </div>

                <div style="overflow: hidden;">
                    <div class="events">
                    <br />
                    <table id="interviews" border="0" width="100%" cellpadding="1" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Select</th>
                        <th>Interview Date</th>
                        <th>Institute</th>
                        <th class="last">Branch</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    </table>
                    <br />
                    <input src="images/register_now.jpg" type="image" name="submit" id="btnRegister" class="fr" />
                    </div>
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">           
              <?php require 'Views/destinations_carousel.phtml';?>            
              <?php require 'Views/twitter_feed.phtml'?>    
        </div>
        <!-- Right Content End Here -->        
    </div>
    
</div>
<!-- Content End Here -->
<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='Events']").addClass('active');                                                   
     });
 </script>
<?php include_once 'Views/footer.phtml'; ?>                                                