<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>><span>Upcoming Admission Interviews</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Upcoming Admission Interviews</h3>
                Here is your opportunity to meet with the officials from overseas institutions directly. To enroll for an interview session, please select our branch closest to you:<br /><br />
                <div id="divSels" style="display:none;">
                <div class="state fl" style="width: 230px; margin-right: 10px;">
                    <label>State</label>
                    <div class="frm_txt_box_container">
                        <select id="selState" class="txt_box"></select>
                    </div>
                </div>
                <div style="width: 20px; float: left;">&nbsp;</div>
                <div class="city fl" style="width: 230px;">
                    <label>City</label>
                    <div class="frm_txt_box_container">
                    <select id="selCity" class="txt_box"></select>
                    </div>
                </div>
                    <div id="errorDiv" style="color:Red; display:none;">No data found</div>
                <div style="clear:both;" id="addressContainer" class="address_box"></div>
                </div>

                <div style="overflow: hidden;">
                    <div class="events">
                    <br />
                    <table id="interviews" border="0" width="100%" cellpadding="1" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Select</th>
                        <th>Interview Date</th>
                        <th>Institute</th>
                        <th class="last">Branch</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    </table>
                    <br />
                    <input src="images/register_now.jpg" type="image" name="submit" id="btnRegister" class="fr" />
                    </div>
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">           
              <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="#" class="prev"></a>
                <div class="credential_scoller">            
                <div class="jCarouselLite">
                    <ul>
                        <li><img src="images/airc_logo.png" alt="American International Recruitment Council" /></li>
                    <li><img src="images/evisa_logo.png" alt="eVisa" /></li>              
                    <li><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent" /></li>                        
                    <li><img src="images/aaeri_logo.png" alt="Education In Australia" /></li>
                    <li><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010" /></li>
                    <li><img src="images/brw_award.png" alt="BRW Fast 100 Award" /></li>
                    <li><img src="images/coco_logo.png" alt="Company Owned Company Operated" /></li>
                    </ul>
                </div>
                </div>
                <a href="#" class="next"></a>
            </div>
            
            <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
		<img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
        </div>
        <!-- University Banner Script End Here -->
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->
<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='Events']").addClass('active');                                                   
     });
 </script>
<?php include_once 'Views/footer.phtml'; ?>                                                