<?php require('Views/header_'.$view->headerTitle.'.phtml');?>

<!-- Content Start From Here -->
<div id="content">
	
    <!-- Left Content Start From Here -->
    <div id="lt_container">
    	<div id="box_container" style="margin-top: 4px;">
        	<div class="box">
                <h3>Meet The Institutions</h3>
                <p>Here is your opportunity to meet with the officials from overseas institutions directly. To enroll for an interview session, please select our branch...</p>
                <p><a href="events.html" title="Meet the institutions"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;"></a></p>
            </div>
            <div class="box lt_mrgn">
            	<h3>Services</h3>
                <p>We understand the challenges faced by those aspiring to study overseas. Keeping in mind the needs of such students, we have designed our...</p>
                <p><a href="services.html" title="Services"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;"></a></p>
            </div>
            <div class="box">
            	<h3>News</h3>
                <p>We believe it is important to stay informed about what is happening in the international education industry, not just in India, but in the countries we...</p>
                <p><a href="news_room.html" title="News"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;"></a></p>
            </div>
            <div class="box lt_mrgn">
            	<h3>Study Destinations</h3>
                <p>At ISRA Consultants we represent some of the leading education institutes across Australia, Canada, New Zealand, the UK and the USA...</p>
                <p><a href="StudyDestinations.php" title="Study Destinations"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;"></a></p>
            </div>
        </div>
    </div>
    <!-- Left Content End Here -->
    
    <!-- Right Content Start From Here -->
    <div id="rt_container">
    	<div class="credentials">        	
        	<a href="index.html#" class="prev"></a>
        	<div class="credential_scoller" style="visibility: visible; overflow: hidden; position: relative; z-index: 2; left: 0px;">            
            <div class="jCarouselLite">
                <ul style="margin: 0px; padding: 0px; position: relative; list-style-type: none; z-index: 1; width: 1014px; left: -234px;"><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                	<li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li>
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li>              
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li>                        
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aaeri_logo.png" alt="Education In Australia"></li>
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li>
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li>
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li></ul>
            </div>
            </div>
            <a href="index.html#" class="next"></a>
        </div>
        
        <!-- University Banner Script Start From Here -->
      <!--  <div style="overflow: hidden;">
      
        <div style="border: none; margin-top: 15px;"><iframe src="./ISRAWeb_files/university_banners.htm" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
		<img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;">
        </div>-->
        <div class="credentials" style="margin-top: 10px">  
        <marquee direction="up" align="middle" onmouseover="this.stop();" onmouseout="this.start();" scrolldelay="0" scrollamount="2" style="height: 80px; margin-top: 3px">
                                                        <div align="center">
                                                        <a href="http://www.tees.ac.uk/" target="_blank"><img src="images/teesside_university.png" alt="Teesside University" width="174" height="108" border="0" title="Teesside University"></a> <br>
                                                          <strong><a href="http://www.tees.ac.uk/" target="_blank" class="more">Teesside University</a></strong>
                                                          <br>
														  <br>
                                                                                                                  
                                                        <a href="http://liverpool.ac.uk/" target="_blank"><img src="images/u_liverpool.png" alt="University of Liverpool" width="174" height="108" border="0" title="University of Liverpool"></a> <br>
                                                          <strong><a href="http://liverpool.ac.uk/" target="_blank" class="more">University of Liverpool</a></strong>
                                                          <br>
														  <br>
                                                          
                                                          <a href="http://www.mdx.ac.uk/" target="_blank"><img src="images/u_middlesex.png" alt="Middlesex University" width="174" height="108" border="0" title="Middlesex University"></a> <br>
                                                          <strong><a href="http://www.mdx.ac.uk/" target="_blank" class="more">Middlesex University</a></strong>
                                                          <br>
														  <br>
                                                        
                                                        
                                                        
                                                        <a href="http://www.lboro.ac.uk/" target="_blank"><img src="images/u_lboro_logo.png" alt="University of Loughborough" width="174" height="108" border="0" title="University of Loughborough"></a> <br>
                                                          <strong><a href="http://www.lboro.ac.uk/" target="_blank" class="more">University of Loughborough</a></strong>
                                                          <br>
														  <br>
                                                          
                                                          <a href="http://www.uea.ac.uk/" target="_blank"><img src="images/u_uea_logo.png" alt="University of East Anglia" width="174" height="108" border="0" title="University of East Anglia"></a> <br>
                                                          <strong><a href="http://www.uea.ac.uk/" target="_blank" class="more">University of East Anglia</a></strong>
                                                          <br>
														  <br>
                                                          <a href="http://www.ntu.ac.uk/" target="_blank"><img src="images/u_ntu_logo.png" alt="Nottingham Trent University" width="174" height="108" border="0" title="Nottingham Trent University"></a> <br>
                                                          <strong><a href="http://www.ntu.ac.uk/" target="_blank" class="more">Nottingham Trent University</a></strong>
                                                          <br>
														  <br>
                                                          <a href="http://www.essex.ac.uk/" target="_blank"><img src="images/u_essex_logo.png" alt="University of Essex" width="174" height="108" border="0" title="University of Essex "></a> <br>
                                                          <strong><a href="http://www.essex.ac.uk/" target="_blank" class="more">University of Essex </a></strong>
                                                          <br>
														  <br>
                                                          <a href="http://www.derby.ac.uk/" target="_blank"><img src="images/u_derby_logo.png" alt="University of Derby" width="174" height="108" border="0" title="University of Derby"></a> <br>
                                                          <strong><a href="http://www.derby.ac.uk/" target="_blank" class="more">University of Derby</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.bangor.ac.uk/" target="_blank"><img src="images/u_bangor_logo.png" alt="University of Wales Bangor" width="174" height="108" border="0" title="University of Wales Bangor"></a> <br>
                                                          <strong><a href="http://www.bangor.ac.uk/" target="_blank" class="more">University of Wales Bangor </a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.anglia.ac.uk/ruskin/en/home.html" target="_blank"><img src="images/u_anglia_logo.png" alt="Anglia Ruskin University" width="174" height="108" border="0" title="Anglia Ruskin University"></a> <br>
                                                          <strong><a href="http://www.anglia.ac.uk/ruskin/en/home.html" target="_blank" class="more">Anglia Ruskin University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www1.aston.ac.uk/" target="_blank"><img src="images/u_aston_logo.png" alt="Aston University" width="174" height="108" border="0" title="Aston University"></a> <br>
                                                          <strong><a href="http://www1.aston.ac.uk/" target="_blank" class="more">Aston University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.beds.ac.uk/" target="_blank"><img src="images/u_beds_logo.png" alt="University of Bedfordshire" width="174" height="108" border="0" title="University of Bedfordshire"></a> <br>
                                                          <strong><a href="http://www.beds.ac.uk/" target="_blank" class="more">University of Bedfordshire</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.bolton.ac.uk/" target="_blank"><img src="images/u_bolton_logo.png" alt="University of Bolton" width="174" height="108" border="0" title="University of Bolton"></a> <br>
                                                          <strong><a href="http://www.bolton.ac.uk/" target="_blank" class="more">University of Bolton</a></strong>
														  <br>
														  <br>
                                                          <a href="http://wwwm.coventry.ac.uk/Pages/index.aspx" target="_blank"><img src="images/u_conventry_logo.png" alt="Conventry University" width="174" height="108" border="0" title="Conventry University"></a> <br>
                                                          <strong><a href="http://wwwm.coventry.ac.uk/Pages/index.aspx" target="_blank" class="more">Conventry University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.exeter.ac.uk/" target="_blank"><img src="images/u_exeter_logo.png" alt="University of Exeter" width="174" height="108" border="0" title="University of Exeter"></a> <br>
                                                          <strong><a href="http://www.exeter.ac.uk/" target="_blank" class="more">University of Exeter</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.glam.ac.uk/" target="_blank"><img src="images/u_glam_logo.png" alt="University of Glamorgan" width="174" height="108" border="0" title="University of Glamorgan "></a> <br>
                                                          <strong><a href="http://www.glam.ac.uk/" target="_blank" class="more">University of Glamorgan </a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.herts.ac.uk/home-page.cfm" target="_blank"><img src="images/u_herts_logo.png" alt="University of Hertfordshire" width="174" height="108" border="0" title="University of Hertfordshire"></a> <br>
                                                          <strong><a href="http://www.herts.ac.uk/home-page.cfm" target="_blank" class="more">University of Hertfordshire</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.hull.ac.uk/" target="_blank"><img src="images/u_hull_logo.png" alt="University of Hull" width="174" height="108" border="0" title="University of Hull"></a> <br>
                                                          <strong><a href="http://www.hull.ac.uk/" target="_blank" class="more">University of Hull </a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.ljmu.ac.uk/" target="_blank"><img src="images/u_ljmu_logo.png" alt="Liverpool John Moore University" width="174" height="108" border="0" title="Liverpool John Moore University"></a> <br>
                                                          <strong><a href="http://www.ljmu.ac.uk/" target="_blank" class="more">Liverpool John Moore University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.lsbu.ac.uk/" target="_blank"><img src="images/u_lsbu_logo.png" alt="London South Bank University" width="174" height="108" border="0" title="London South Bank University"></a> <br>
                                                          <strong><a href="http://www.lsbu.ac.uk/" target="_blank" class="more">London South Bank University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.mmu.ac.uk/" target="_blank"><img src="images/u_mmu_logo.png" alt="Manchester Metropolitan University" width="174" height="108" border="0" title="Manchester Metropolitan University"></a> <br>
                                                          <strong><a href="http://www.mmu.ac.uk/" target="_blank" class="more">Manchester Metropolitan University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.ncl.ac.uk/" target="_blank"><img src="images/u_ncl_logo.png" alt="Newcastle University" width="174" height="108" border="0" title="Newcastle University"></a> <br>
                                                          <strong><a href="http://www.ncl.ac.uk/" target="_blank" class="more">Newcastle University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.port.ac.uk/" target="_blank"><img src="images/u_port_logo.png" alt="University of Portsmouth" width="174" height="108" border="0" title="University of Portsmouth"></a> <br>
                                                          <strong><a href="http://www.port.ac.uk/" target="_blank" class="more">University of Portsmouth</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.salford.ac.uk/" target="_blank"><img src="images/u_salford_logo.png" alt="University of Salford" width="174" height="108" border="0" title="University of Salford"></a> <br>
                                                          <strong><a href="http://www.salford.ac.uk/" target="_blank" class="more">University of Salford</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.sussex.ac.uk/" target="_blank"><img src="images/u_sussex_logo.png" alt="University of Sussex" width="174" height="108" border="0" title="University of Sussex"></a> <br>
                                                          <strong><a href="http://www.sussex.ac.uk/" target="_blank" class="more">University of Sussex</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.swan.ac.uk/" target="_blank"><img src="images/u_swan_logo.png" alt="Swansea University" width="174" height="108" border="0" title="Swansea University"></a> <br>
                                                          <strong><a href="http://www.swan.ac.uk/" target="_blank" class="more">Swansea University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.uclan.ac.uk/" target="_blank"><img src="images/u_uclan_logo.png" alt="University of Central Lancashire" width="174" height="108" border="0" title="University of Central Lancashire"></a> <br>
                                                          <strong><a href="http://www.uclan.ac.uk/" target="_blank" class="more">University of Central Lancashire</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.uel.ac.uk/" target="_blank"><img src="images/u_uel_logo.png" alt="University of East London" width="174" height="108" border="0" title="University of East London"></a> <br>
                                                          <strong><a href="http://www.uel.ac.uk/" target="_blank" class="more">University of East London</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.gcal.ac.uk/" target="_blank"><img src="images/u_gcal_logo.png" alt="Glascow Caledonian Unibversity" width="174" height="108" border="0" title="Glascow Caledonian Unibversity"></a> <br>
                                                          <strong><a href="http://www.gcal.ac.uk/" target="_blank" class="more">Glascow Caledonian Unibversity</a></strong>
                                                          <br>
														  <br>
                                                          <a href="http://www2.astate.edu/" target="_blank"><img src="images/u_asu_logo.png" alt="Arkansas State University" width="174" height="108" border="0" title="Arkansas State University"></a> <br>
<strong><a href="http://www2.astate.edu/" target="_blank" class="more">Arkansas State University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.kingston.ac.uk/" target="_blank"><img src="images/kingston_uni_logo.png" alt="Kingston University" width="174" height="108" border="0" title="Kingston University"></a> <br>
<strong><a href="http://www.kingston.ac.uk/" target="_blank" class="more">Kingston University</a></strong>
														  <br>
														  <br>
                                                          <a href="http://www.wlu.ca/" target="_blank"><img src="images/wlu.png" alt="Wilfrid Laurier University" width="174" height="108" border="0" title="Wilfrid Laurier University"></a> <br>
<strong><a href="http://www.wlu.ca/" target="_blank" class="more">Wilfrid Laurier University</a></strong>

                                                        </div>
														</marquee>
        </div>
        <!-- University Banner Script End Here -->
            
    </div>
    <!-- Right Content End Here -->
    
</div>
<!-- Content End Here -->
<?php include_once 'Views/footer.phtml'; ?>                                                