<?php require('Views/header.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>Newsroom</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Newsroom</h3>
                
                <div style="overflow: hidden;">
                	We believe it is important to stay informed about what is happening in the international education industry, not just in India, but in the countries we work with. Here you will find all of the current news and issues that relate to the industry, visas, and your opportunities to study abroad. Check back here regularly to stay informed!
                </div>
                
                <div style="overflow:hidden;">
                	<div class="innerContent" style="width:100%; margin-left:0px; margin-top:10px;">
                        <div id="accordion">
                            <!--<div id="lstWhatsNew"></div>-->
                        </div>
                    </div>
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">          
            <?php require 'Views/destinations_carousel.phtml';?>
            <?php require 'Views/twitter_feed.phtml'?> 

        </div>
        <!-- Right Content End Here -->        
    </div>
    
</div>
<!-- Content End Here -->
<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='Newsroom']").addClass('active');                                                   
     });
 </script>

<?php include_once 'Views/footer.phtml'; ?>                                                