<?php require('Views/header_'.$view->headerTitle.'.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>><span>Newsroom</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Newsroom</h3>
                
                <div style="overflow: hidden;">
                	We believe it is important to stay informed about what is happening in the international education industry, not just in India, but in the countries we work with. Here you will find all of the current news and issues that relate to the industry, visas, and your opportunities to study abroad. Check back here regularly to stay informed!
                </div>
                
                <div style="overflow:hidden;">
                	<div class="innerContent" style="width:100%; margin-left:0px; margin-top:10px;">
                        <div id="accordion">
                            <!--<div id="lstWhatsNew"></div>-->
                        </div>
                    </div>
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">          
            <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="#" class="prev"></a>
                <div class="credential_scoller">            
                <div class="jCarouselLite">
                    <ul>
                        <li><img src="images/airc_logo.png" alt="American International Recruitment Council" /></li>
                    <li><img src="images/evisa_logo.png" alt="eVisa" /></li>              
                    <li><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent" /></li>                        
                    <li><img src="images/aaeri_logo.png" alt="Education In Australia" /></li>
                    <li><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010" /></li>
                    <li><img src="images/brw_award.png" alt="BRW Fast 100 Award" /></li>
                    <li><img src="images/coco_logo.png" alt="Company Owned Company Operated" /></li>
                    </ul>
                </div>
                </div>
                <a href="#" class="next"></a>
            </div>
            
            <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
		<img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
        </div>
        <!-- University Banner Script End Here -->
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->


<?php include_once 'Views/footer.phtml'; ?>                                                