<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>Privacy Policy</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Privacy Policy</h3>
                
                <div style="overflow: hidden;">
                    <span class="heading">Legal Policy</span><br />
                    ISRA consultants copyright © ISRA consultants India pvt. ltd. you must not disseminate, copy or republish the website content without a written permission from an authorised representative of ISRA consultants australia pty. ltd. all rights reserved with the copyright owner.
                    <br /><br />
                    <span class="heading">Disclaimer</span><br />
                    The disclaimer applies to all content presented on this website. the purpose of our website is to provide information in relation to our profession, however ISRA consultants India pvt. ltd. will not be responsible for any errors or misinterpretations or omissions in this website in relation to the content of the information. you must not take any action based on the information contained in the website.
                    <br /><br />
                    We would request you to use this information on our website only for general awareness purpose and not for individual professional migration advice. for any such personal advice, please contact one of our registered migration agents. the professional representations are only undertaken upon the signing of the cost agreement as agreed by ISRA consultants and the client.
                    <br /><br />
                    The web links to any outbound sites are independent of ISRA consultants. we are not responsible for any information available at any of these websites. any personal information that you might disclose to us is treated with strict confidence. no part of this information is communicated to any authorities or agencies without your consent.
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">
            <?php require 'Views/destinations_carousel.phtml';?>
             <?php require 'Views/twitter_feed.phtml'?> 
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->

<?php include_once 'Views/footer.phtml'; ?>                                                