<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>Privacy Policy</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Privacy Policy</h3>
                
                <div style="overflow: hidden;">
                    <span class="heading">Legal Policy</span><br />
                    Oceanic consultantscopyright © oceanic consultants australia pty. ltd. ABN: 33 095 635 831 you must not disseminate, copy or republish the website content without a written permission from an authorised representative of oceanic consultants australia pty. ltd. all rights reserved with the copyright owner.
                    <br /><br />
                    <span class="heading">Disclaimer</span><br />
                    The disclaimer applies to all content presented on this website. the purpose of our website is to provide information in relation to our profession, however oceanic consultants australia pty. ltd. will not be responsible for any errors or misinterpretations or omissions in this website in relation to the content of the information. you must not take any action based on the information contained in the website.
                    <br /><br />
                    We would request you to use this information on our website only for general awareness purpose and not for individual professional migration advice. for any such personal advice, please contact one of our registered migration agents. the professional representations are only undertaken upon the signing of the cost agreement as agreed by oceanic consultants and the client.
                    <br /><br />
                    The web links to any outbound sites are independent of oceanic consultants. we are not responsible for any information available at any of these websites. any personal information that you might disclose to us is treated with strict confidence. no part of this information is communicated to any authorities or agencies without your consent.
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">
            <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="#" class="prev"></a>
                <div class="credential_scoller">            
                <div class="jCarouselLite">
                    <ul>
                        <li><img src="images/airc_logo.png" alt="American International Recruitment Council" /></li>
                    <li><img src="images/evisa_logo.png" alt="eVisa" /></li>              
                    <li><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent" /></li>                        
                    <li><img src="images/aaeri_logo.png" alt="Education In Australia" /></li>
                    <li><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010" /></li>
                    <li><img src="images/brw_award.png" alt="BRW Fast 100 Award" /></li>
                    <li><img src="images/coco_logo.png" alt="Company Owned Company Operated" /></li>
                    </ul>
                </div>
                </div>
                <a href="#" class="next"></a>
            </div>
            
            <div style="overflow: hidden;">
            <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
			<img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
            </div>
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->

<?php include_once 'Views/footer.phtml'; ?>                                                