<?php require('Views/header.phtml');?>

<style type="text/css">
a {
	color: #FFF;
}
fieldset
{
	width: 556px;
	margin: 3px 3px 8px 3px;
	padding: 5px;
	padding-left: 10px;
	text-align: center;
	border: solid 1px #dadfe0;
	background: url(images/grey_grdn_bg.jpg) repeat-x;
	font-size: 11px;
}
.im {
	position: relative;
}
h3.heading_red {
	color: #b60000;
	font-weight: normal;
	font-size: 11px;
}
.inputForm {
	color:#666;
	font-size:11px;
	padding: 1px;
}
.inputReg {
	padding: 0px;
	color:#666;
	font-size:11px;
	border: solid 1px #bbb;
	padding: 2px;
}
h3 {
	margin:10px 0px 0px 5px;
	font:bold 11px Arial, Helvetica, sans-serif;
}
fieldset legend
{
	padding: 5px 10px;
	font-weight: bold;
	
}
body
{
	margin: 0px;
	padding: 0px;
	color: #504E4E;
	font: 11px Arial,Helvetica,sans-serif;
	font-size: 11px;
}
div.formRow
{
	padding: 3px 0px 3px 10px;
	clear: both;
}
div.fieldContainer
{
	clear: none;
	float: left;
	padding-right: 10px;
	padding-bottom: 10px;
}
div.fieldLabel
{
	float: left;
	clear: right;	
}
div.field
{
	float: left;
	clear: left;
}
div.field input
{
	width: 258px;
	font-size:11px;
	color:#666;
}
div.field input.big
{
	width: 500px;
}
div.field select
{
	width: 258px;
}

div.mainForm label
{
	width: auto;
	text-align: left;
	margin-right: 3px;
}
.fl {
	width: 250px;
	float: left;
	overflow: hidden;
}
.btn {
	padding: 5px 10px;
	border: solid 1px #C7C7C7;
	background: #E7E7E7;
	margin-bottom: 10px;
}
</style>

<!-- Content Start From Here -->
<div id="content_container">
    
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
        <div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>><span>Free Registration</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
    
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Free Registration</h3>
                
   				<table border="0" cellpadding="5" cellspacing="0" width="556">
                <tr>  
                <td>
                <form method="post" action="<?php echo $_SERVER["PHP_SELF"]?>" onsubmit="javascript:return WebForm_OnSubmit();" id="form1">
        <div class="wrapper">
            
                    <div class="pageContent">
                        <div id="register">
                            <div class="content" style="background-color: #fff; margin-bottom: 5px;">
                                <span style="font-size: 11px;">Please provide us the following details and we will call you as soon as possible.</span>
                                
                                <div><h3 class="heading_red">Personal Details</h3>
                                    <fieldset>
                                        
                                            <div class="formRow">
                                                <div class="fieldContainer">
                                                    <div class="field" style="margin-top: 14px;">
                                                    <select name="title" id="title" class="inputForm" align="left" style="width:50px;">
	<option value="71">Mr</option>
	<option value="72">Mrs</option>
	<option value="73">Miss</option>
	<option value="74">Ms</option>
	<option value="75">Dr</option>
	<option value="76">Prof</option>

</select>
                                                    </div>
                                                </div>
                                                
                                                <div class="fieldContainer" id="myFormControl2">
                                                    <div class="fieldLabel">First name*</div>
                                                    <div class="field">
                                                        <input name="firstname" type="text" maxlength="100" id="firstname" class="inputReg" style="width:120px;" />
                                                        </div>
                                                </div>
                                            
                                                <div class="fieldContainer" id="myFormControl2">
                                                    <div class="fieldLabel">Last Name*</div>
                                                    <div class="field">
                                                        <input name="lastname" type="text" maxlength="100" id="lastname" class="inputReg" style="width:150px;" />
                                                        </div>
                                                </div>
                                                
                                            </div>
                                            <!-- comment here-->
                                            <div class="formRow">
                                            
                                                <div class="fieldContainer" id="myFormControl3">
                                                    <div class="fieldLabel">Date of birth
                                                        </div>
                                                    <div class="field">                                                        
                                                        <input name="dob" type="text" value="dd/mm/yyyy" maxlength="100" id="datepicker" class="inputReg" style="width:160px;" />
                                                    </div>
                                                </div>
                                                
                                                <div class="fieldContainer" id="myFormControl6">
                                                    <div class="fieldLabel">Mobile no. </div>
                                                    <div class="field">
                                                        <input name="mobileno" type="text" maxlength="50" id="mobileno" class="inputReg" style="width:150px;" />
                                                    </div>
                                                </div>
                                                
                                            </div>    
                                            <div class="formRow">                                                
                                                <div id="myFormControl11" class="fieldContainer">
                                                    <div class="fieldLabel">Street Address</div>
                                                    <div class="field">
                                                        <input name="streetaddress" type="text" id="streetaddress" class="inputReg" style="width:180px;" />
                                                    </div>
                                                </div>
                                                
                                                <div class="fieldContainer">
                                                    <div class="fieldLabel">State of residence
                                                        <span id="ReqStudentstate" title="select state" style="display:none;"><img id="imgphone" title="select state" alt="select state" src="images/crossRed16.gif" /></span>
                                                    </div>
                                                    <div class="field">
                                                        <select name="state" id="state" class="inputReg" align="left" style="width:158px;">
	<option value="0">--select--</option>        
	<option value="33">Andaman &amp; Nicobar Islands</option>
	<option value="5">Andhra Pradesh</option>
	<option value="6">Arunachal Pradesh</option>
	<option value="7">Assam</option>
	<option value="8">Bihar</option>
	<option value="3">Chandigarh</option>
	<option value="9">Chattisgarh</option>
	<option value="34">Dadra and Nagar Haveli</option>
	<option value="35">Daman and Diu</option>
	<option value="4">Delhi</option>
	<option value="10">Goa</option>
	<option value="11">Gujarat</option>
	<option value="12">Haryana</option>
	<option value="13">Himachal Pradesh</option>
	<option value="14">Jammu and Kashmir</option>
	<option value="15">Jharkhand </option>
	<option value="16">Karnataka </option>
	<option value="17">Kerala</option>
	<option value="36">Lakshadweep</option>
	<option value="18">Madhya Pradesh</option>
	<option value="19">Maharashtra</option>
	<option value="20">Manipur</option>
	<option value="21">Meghalaya</option>
	<option value="22">Mizoram</option>
	<option value="23">Nagaland</option>
	<option value="38">New Delhi</option>
	<option value="24">Orissa</option>
	<option value="37">Pondicherry</option>
	<option value="25">Punjab</option>
	<option value="26">Rajasthan</option>
	<option value="27">Sikkim</option>
	<option value="28">Tamil Nadu</option>
	<option value="29">Tripura</option>
	<option value="31">Uttar Pradesh</option>
	<option value="30">Uttarakhand</option>
	<option value="32">West Bengal</option>
        <option value="34">Other</option>
                                                        </select>
                                                        </div>
                                                </div>
                                                
                                           </div>
                                           <div class="formRow">
                                           
                                                <div id="myFormControl12" class="fieldContainer">
                                                    <div class="fieldLabel">City of residence  </div>
                                                    <div class="field">
                                                        <input name="city" type="text" maxlength="50" id="city" class="inputReg" style="width:180px;" />
                                                    </div>
                                                </div>
                                                
                                                <div class="fieldContainer">
                                                    <div class="fieldLabel">Email*
                                                         </div>
                                                    <div class="field">
                                                        <input name="emailid" type="text" maxlength="100" id="emailid" class="inputReg" style="width:150px;" />
                                                    </div>
                                                </div>
                                                
                                            </div>                  
                                    </fieldset>
                                    </div>                
         
                                    
                                    <div><h3 class="heading_red">Study preferences</h3>
                                    <fieldset>                        	                            
                                        <p align="left" style="margin-left: 10px;">Preferred country <span>[you may select multiple destinations]</span></p>
                                        <div class="formRow">
                                            <div class="fieldContainer" style="margin-left: -10px;">
                                                <div id="UpdatePanel1">
	
                                                <table id="interestedCountry" class="ckbBx" style="width:500px;">
		<tr>
			<td><input id="interestedCountry_0" type="checkbox" name="interestedCountry0" value="12" />
                            <label for="interestedCountry_0">Australia</label></td>
                        <td><input id="interestedCountry_1" type="checkbox" name="interestedCountry1" value="39" /><label for="interestedCountry_1">Canada</label></td>
                        <td><input id="interestedCountry_2" type="checkbox" name="interestedCountry2" value="181" /><label for="interestedCountry_2">New Zealand</label></td>
                        <td><input id="interestedCountry_3" type="checkbox" name="interestedCountry3" value="240" /><label for="interestedCountry_3">United Kingdom</label></td>
                        <td><input id="interestedCountry_4" type="checkbox" name="interestedCountry4" value="242" /><label for="interestedCountry_4">USA</label></td>
		</tr>
	</table>
                                                
</div>								
                                            </div>
                                        </div>
                                        
                                        <div style="width:10px; height:5px; clear:both;"></div>                                  
                                    <div id="Div2" style="padding-left: 10px;">
                                        <div style="width: 280px; display: block;"><p>Qualifications [you may specify multiple awards achieved]</p></div>
                                        <div id="ddlawards" class="RadComboBox RadComboBox_Default" style="float:left">
                                            <textarea id="qualifications" name="qualifications" style="margin: 0px; width: 385px; height: 87px;"></textarea>
                                        </div>                                     
                                    <br />
                                </div>                                   
                                <br />
                                <div id="myFormControl10" style="display: block; clear: both; margin-top: 20px; margin-left: 10px;padding-top: 10px; padding-bottom: 5px;">
                                    <div align="left">
                                        <input type="submit" name="btnsubmit" value="Submit" onclick="" id="btnsubmit" class="btn" />                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                  
                </div>          
       
</form>
                </td>
                </tr>
                </table>
                    
    		</div> 
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">
              <?php require 'Views/destinations_carousel.phtml';?>
              <?php require 'Views/twitter_feed.phtml'?> 
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->


<?php include_once 'Views/footer.phtml'; ?>                                                