<?php require('Views/header_'.$view->headerTitle.'.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>&gt;<span>Services</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right"></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Services</h3>
                
                <div style="overflow: hidden;">
                    With more than 10 years of experience in placing thousands of students in various institutions overseas, we understand the challenges faced by those aspiring to study overseas. Keeping in mind the needs of such students, we have designed our processes in a manner that every single task starting from admission to visa to making travel arrangements is smooth and hassle free.
                    <br><br>
                    Our dedicated team is there to help you with every stage of the process.
                </div>
                
                <div style="overflow: hidden;">
                    <br><br>
                    <div class="lt_box">
                        <h3 class="heading_small">Course Selection</h3>
                        We help you choose the destination, course and institution that matches your personal circumstances such as academic, employment and financial background. While helping you make these choices we will also take into consideration your long term goals such as your career aspirations.
                    </div>
                    <div class="rt_box">
                        <h3 class="heading_small">Getting Admission</h3>
                        Navigating the admission process of your chosen education institution can often be a confusing process. At ISRA we help to make things easier. We also coordinate with the relevant institution admission office on your behalf to ensure the process progresses as efficiently as possible.
                    </div>
                </div>
                
                <div style="overflow: hidden;">
                    <br><br>
                    <div class="lt_box">
                        <h3 class="heading_small">Student Visa</h3>
                        We provide complete assistance with student visa applications. This includes providing advice on the documentation required for the student visa, lodging the student visa application and coordinating the same on your behalf with the concerned visa office.
                    </div>
                    <div class="rt_box">
                        <h3 class="heading_small">Travel Arrangements</h3>
                        Through our partnerships with leading service providers, we can take care of all your travel needs including air ticketing, foreign exchange and travel insurance.
                    </div>
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">            
            <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="http://www.oceanicconsultants.com/services.html#" class="prev"></a>
                <div class="credential_scoller" style="visibility: visible; overflow: hidden; position: relative; z-index: 2; left: 0px;">            
                <div class="jCarouselLite">
                    <ul style="margin: 0px; padding: 0px; position: relative; list-style-type: none; z-index: 1; width: 1014px; left: -234px;"><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li>              
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li>                        
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aaeri_logo.png" alt="Education In Australia"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010"></li>                                    
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/brw_award.png" alt="BRW Fast 100 Award"></li>
                        <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/coco_logo.png" alt="Company Owned Company Operated"></li>
                    <li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/airc_logo.png" alt="American International Recruitment Council"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/evisa_logo.png" alt="eVisa"></li><li style="overflow: hidden; float: left; width: 77px; height: 59px;"><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent"></li></ul>
                </div>
                </div>
                <a href="http://www.oceanicconsultants.com/services.html#" class="next"></a>
            </div>            
            
            <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="images/university_banners.htm" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
		<img src="http://www.oceanicconsultants.com/images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;">
        </div>
        <!-- University Banner Script End Here -->
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->

<?php include_once 'Views/footer.phtml'; ?>                                                