<?php require('Views/header.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>&gt;<span>Services</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right"></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Services</h3>
                
                <div style="overflow: hidden;">
                    With more than 10 years of experience in placing thousands of students in various institutions overseas, we understand the challenges faced by those aspiring to study overseas. Keeping in mind the needs of such students, we have designed our processes in a manner that every single task starting from admission to visa to making travel arrangements is smooth and hassle free.
                    <br><br>
                    Our dedicated team is there to help you with every stage of the process.
                </div>
                
                <div style="overflow: hidden;">
                    <br><br>
                    <div class="lt_box">
                        <h3 class="heading_small">Course Selection</h3>
                        We help you choose the destination, course and institution that matches your personal circumstances such as academic, employment and financial background. While helping you make these choices we will also take into consideration your long term goals such as your career aspirations.
                    </div>
                    <div class="rt_box">
                        <h3 class="heading_small">Getting Admission</h3>
                        Navigating the admission process of your chosen education institution can often be a confusing process. At ISRA we help to make things easier. We also coordinate with the relevant institution admission office on your behalf to ensure the process progresses as efficiently as possible.
                    </div>
                </div>
                
                <div style="overflow: hidden;">
                    <br><br>
                    <div class="lt_box">
                        <h3 class="heading_small">Student Visa</h3>
                        We provide complete assistance with student visa applications. This includes providing advice on the documentation required for the student visa, lodging the student visa application and coordinating the same on your behalf with the concerned visa office.
                    </div>
                    <div class="rt_box">
                        <h3 class="heading_small">Travel Arrangements</h3>
                        Through our partnerships with leading service providers, we can take care of all your travel needs including air ticketing, foreign exchange and travel insurance.
                    </div>
                </div>
                            
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">            
            <?php require 'Views/destinations_carousel.phtml';?>
            <?php require 'Views/twitter_feed.phtml'?>    
        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->

<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='Services']").addClass('active');                                                   
     });
 </script>
<?php include_once 'Views/footer.phtml'; ?>                                                