<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>Study Destinations</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->

    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container1">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt1">
                <h3 class="heading">Study Destinations</h3>
                
                <div style="overflow: hidden; height: 320px;">
                    <div class="lt">
                        <img src="images/study_destinations_banner.jpg" alt="Study Destinations" width="437" height="279" border="0" usemap="#Map2" />
                        <map name="Map2" id="Map2">
                        <area shape="poly" coords="304,157,343,168,314,203,218,227,216,191" href="StudyInNewZealand.php" title="Study in New Zealand" />
                        <area shape="poly" coords="304,79,343,90,314,125,218,149,216,113" href="StudyInCanada.phpl" title="Study in Canada" />
                        <area shape="poly" coords="61,127,102,117,192,153,189,186,95,163" href="StudyInTheUk.php" title="Study in the UK" />
                        <area shape="poly" coords="61,52,102,42,192,78,189,111,95,88" href="StudyInTheUSA.php" title="Study in the USA" />
                        <area shape="poly" coords="304,9,343,20,314,55,218,79,216,43" href="StudyInAustralia.php" title="Study in Australia" />
                        </map>
                  </div>
                    
                    <div class="rt">
                        <div>
                            <p>At ISRA Consultants we represent some of the leading education institutes across Australia, Canada, New Zealand, the United Kingdom and the USA. From Diploma and pathways options through to undergraduate and postgraduate courses, we can offer students a choice of course and institution in a wide variety of cities and towns within these countries.
                            <br /><br />
                            Our dedicated team is there to help you with every stage of the process.
                            </p>
                        </div>
                            
                      
                    </div>                
                </div>
                
                <div style="overflow: hidden;">
                    <div id="country_ticker">
                        <h3>Study in <span>Australia</span></h3>
                        <a href="StudyInAustralia.php" class="fullBg" title="Study in Australia"></a>                    
                        <div class="aus">&nbsp;</div>
                        <div class="cnt">Australia offers students quality education options coupled with a great lifestyle. Click here to find out more information.</div>
                        <a href="StudyInAustralia.php" title="Study in Australia"><img src="images/read_more_btn.jpg" width="110" height="34" alt="Read More" border="0" /></a>
                    </div>
                    <div id="country_ticker">
                    <a href="StudyInCanada.php" class="fullBg" title="Study in Canada"></a>
                        <h3>Study in <span>Canada</span></h3>                    
                        <div class="canada">&nbsp;</div>
                        <div class="cnt">Canada offers students great opportunities as a study destination, with an award winning lifestyle and multicultural population.</div>
                        <a href="StudyInCanada.php" title="Study in Canada"><img src="images/read_more_btn.jpg" width="110" height="34" alt="Read More" border="0" /></a>
                    </div>
                    <div id="country_ticker">
                    <a href="StudyInNewZealand.php" class="fullBg" title="Study in New Zealand"></a>
                        <h3>Study in <span>NZ</span></h3>                    
                        <div class="newzealand">&nbsp;</div>
                        <div class="cnt">A small but diverse country with an amazing natural environment, New Zealand is a great choice for International students.</div>
                        <a href="StudyInNewZealand.php" title="Study in New Zealand"><img src="images/read_more_btn.jpg" width="110" height="34" alt="Read More" border="0" /></a>
                    </div>
                    <div id="country_ticker">
                    <a href="StudyInTheUk.php" class="fullBg" title="Study in the UK"></a>
                        <h3>Study in the <span>UK</span></h3>                    
                        <div class="uk">&nbsp;</div>
                        <div class="cnt">A country rich in history and home to a cosmopolitan society, the UK offers students study opportunities in England, Ireland, Scotland and Wales.</div>
                        <a href="StudyInTheUk.php" title="Study in the UK"><img src="images/read_more_btn.jpg" width="110" height="34" alt="Read More" border="0" /></a>
                    </div>
                    <div id="country_ticker">
                    <a href="StudyInTheUSA.php" class="fullBg" title="Study in the USA"></a>
                        <h3>Study in the <span>US</span></h3>                    
                        <div class="usa">&nbsp;</div>
                        <div class="cnt">Well recognized qualifications, and diverse study options across the country, make the USA a great destination for International students.</div>
                        <a href="StudyInTheUSA.php" title="Study in the US"><img src="images/read_more_btn.jpg" width="110" height="34" alt="Read More" border="0" /></a>
                    </div>
                    
                    
                    
                </div>
                
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
      
    </div>
</div>
<!-- Content End Here -->


<?php include_once 'Views/footer.phtml'; ?>                                                