<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">

	<!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>> <a href="StudyDestinations.php" title="Study Detinations">Study Destinations</a>><span>Study in Australia</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
    
<div id="content">
	
    <!-- Left Content Start From Here -->
    <div id="lt_container">
    	<h3 class="countryPage">My Options</h3>
        <!-- Content Start From Here -->
    	<div class="vertMenu">         
         <ul>
         <li><a href="study-in-australia/student-visa-process.html" title="Student visa process"><span>4</span>Student visa process</a></li>
         <li><a href="study-in-australia/list-of-institutions.html" title="List of institutions"><span>4</span>List of institutions</a></li>
         <li><a href="study-in-australia/upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
         <li><a href="study-in-australia/whats-new.html" title="Whats new"><span>4</span>What's new</a></li>
         <li><a href="study-in-australia/work-rights.html" title="Work rights during studies"><span>4</span>Work rights during studies</a></li>
         <li><a href="study-in-australia/post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights</a></li>
         <li><a href="study-in-australia/bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
         <li><a href="study-in-australia/students-under-18-years.html" title="Students under 18 years"><span>4</span>Students under 18 years</a></li>
         <li><a href="study-in-australia/visitor-visa.html" title="Visitor visa"><span>4</span>Visitor visa</a></li>
         </ul>
        </div>
        <div class="gap20 fl"></div>
        <div class="innerContent">
        <p>ISRA Consultants has been helping Indian students Study in Australia for over 10 years. We offer students the choice of Universities, TAFE Colleges and private colleges throughout Australia. ISRA Consultants are a member of The Association of Australian Education Representatives in India (AAERI), and our strong reputation has been acknowledged by the Australian Government making ISRA one of the few agents in India with eVisa lodgement authority.
        <br /><br />
        ISRA Consultants is an Indian company and we are proud to have been awarded several prominent Australian business awards:
        
        </p>
        <p><strong>For more details please click the left menu options.</strong></p>        
        </div>
        <!-- Content End Here -->
        
    </div>
    <!-- Left Content End Here -->
    
   !-- Right Content Start From Here -->
	<div id="rt_container">
         <?php require 'Views/twitter_feed.phtml'?>
            <!-- University Banner Script End Here -->
            </div>
    </div>
    <!-- Right Content End Here -->


<?php include_once 'Views/footer.phtml'; ?>                                                