<?php require('Views/header.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">

	<!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>> <a href="study_destinations.html" title="Study Detinations">Study Destinations</a>><span>Study in the UK</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
    
<div id="content">
	
    <!-- Left Content Start From Here -->
    <div id="lt_container">
    	<h3 class="countryPage">My Options</h3>
        <!-- Content Start From Here -->
    	<div class="vertMenu">
         
         <ul>
         <li><a href="study-in-the-uk/student-visa-process.html" title="Student visa process"><span>4</span>Student visa process</a></li>
         <li><a href="study-in-the-uk/list-of-institutions.html" title="List of institutions"><span>4</span>List of institutions</a></li>
         <li><a href="study-in-the-uk/upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
         <li><a href="study-in-the-uk/whats-new.html" title="What's new"><span>4</span>What's new</a></li>
         <li><a href="study-in-the-uk/work-rights.html" title="Work rights during studies"><span>4</span>Work rights during studies</a></li>
         <li><a href="study-in-the-uk/post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights</a></li>
         <li><a href="study-in-the-uk/bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
         <li><a href="study-in-the-uk/visitor-visa.html" title="Visitor visa"><span>4</span>Visitor visa</a></li>
         <li><a href="study-in-the-uk/studentsunder18years.html" title="Students under 18 years"><span>4</span>Students under 18 years</a></li>
         </ul>
        </div>
        <div class="gap20 fl"></div>
        <div class="innerContent">          
        <p>ISRA Consultants has been helping Indian students Study in the UK   since 2007. We represent Universities and Colleges across England and   Scotland offering students a wide choice of study destination and course   selection.  Many of our staff have successfully completed training   provided by the British Council to ensure our knowledge of living and   studying in the UK is up to date and accurate.</p>

<p><strong>for more details please click the left menu options.</strong></p>

        
        </div>
        <!-- Content End Here -->
        
    </div>
    <!-- Left Content End Here -->
    
    <!-- Right Content Start From Here -->
	<div id="rt_container">
        <div class="facts_container">
        	<ul id="facts">
				<li><img src="images/facts/uk/uk_1.jpg" width="300" height="105" alt="Nowhere in the Britain is more than 74 miles from the sea." /></li>
                <li><img src="images/facts/uk/uk_2.jpg" width="300" height="105" alt="Inner London has the highest GDP per capita (Euro 88,761) of any European city." /></li>
                <li><img src="images/facts/uk/uk_3.jpg" width="300" height="105" alt="Queen Anne had 17 children, all of them died before she did." /></li>
                <li><img src="images/facts/uk/uk_4.jpg" width="300" height="105" alt="Rudolf Hess was the last prisoner to be kept in the Tower of London." /></li>
                <li><img src="images/facts/uk/uk_5.jpg" width="300" height="105" alt="The United Kindom has a coastline of 12,429 km." /></li>
			</ul>        
        </div>
        <!-- University Banner Script Start From Here -->
            <div style="overflow: hidden;">
            <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
            <img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
            </div>
            <!-- University Banner Script End Here -->
            </div>
    </div>
    <!-- Right Content End Here -->
    
</div>
</div>
<!-- Content End Here -->



<?php include_once 'Views/footer.phtml'; ?>                                                