<?php require('Views/header_'.$view->headerTitle.'.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">

	<!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>> <a href="study_destinations.html" title="Study Detinations">Study Destinations</a>><span>Study in Australia</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
    
<div id="content">
	
    <!-- Left Content Start From Here -->
    <div id="lt_container">
    	<h3 class="countryPage">My Options</h3>
        <!-- Content Start From Here -->
    	<div class="vertMenu">
         
         <ul>
         <li><a href="study-in-australia/student-visa-process.html" title="Student visa process"><span>4</span>Student visa process</a></li>
         <li><a href="study-in-australia/list-of-institutions.html" title="List of institutions"><span>4</span>List of institutions</a></li>
         <li><a href="study-in-australia/upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
         <li><a href="study-in-australia/whats-new.html" title="Whats new"><span>4</span>What's new</a></li>
         <li><a href="study-in-australia/work-rights.html" title="Work rights during studies"><span>4</span>Work rights during studies</a></li>
         <li><a href="study-in-australia/post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights</a></li>
         <li><a href="study-in-australia/bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
         <li><a href="study-in-australia/students-under-18-years.html" title="Students under 18 years"><span>4</span>Students under 18 years</a></li>
         <li><a href="study-in-australia/visitor-visa.html" title="Visitor visa"><span>4</span>Visitor visa</a></li>
         </ul>
        </div>
        <div class="gap20 fl"></div>
        <div class="innerContent">
        <p>ISRA Consultants has been helping Indian students Study in Australia for over 17 years. We offer students the choice of Universities, TAFE Colleges and private colleges throughout Australia. ISRA Consultants are a member of The Association of Australian Education Representatives in India (AAERI), and our strong reputation has been acknowledged by the Australian Government making ISRA one of the few agents in India with eVisa lodgement authority.
        <br /><br />
        ISRA Consultants is an Australian company and we are proud to have been awarded several prominent Australian business awards:
        <ul>
        <li>Listed as #32 fastest growing company in Australia by BRW magazine in 2008</li>
        <li>Winner of the Australian Business Awards three years in a row (2008, 2009, 2010)</li>
        </ul>
        </p>
        <p><strong>For more details please click the left menu options.</strong></p>        
        </div>
        <!-- Content End Here -->
        
    </div>
    <!-- Left Content End Here -->
    
    <!-- Right Content Start From Here -->
	<div id="rt_container">
        <div class="facts_container">
        	<ul id="facts">
				<li><img src="images/facts/aus/aus_1.jpg" width="300" height="105" alt="Wallaman Falls, QLD is the tallest waterfall in Australia." /></li>
                <li><img src="images/facts/aus/aus_2.jpg" width="300" height="105" alt="Fraser Island in Australia is the world's largest island." /></li>
                <li><img src="images/facts/aus/aus_3.jpg" width="300" height="105" alt="35% of Australia is classified as desert." /></li>
                <li><img src="images/facts/aus/aus_4.jpg" width="300" height="105" alt="Australia is the 6th largest country in the world." /></li>
                <li><img src="images/facts/aus/aus_5.jpg" width="300" height="105" alt="The Sydney Opera House was designed by Joern Utzon." /></li>
			</ul>        
        </div>
        <!-- University Banner Script Start From Here -->
        <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
        <img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
        </div>
        <!-- University Banner Script End Here -->
    </div>
    <!-- Right Content End Here -->
    
</div>
</div>
<!-- Content End Here -->


<?php include_once 'Views/footer.phtml'; ?>                                                