<?php require('Views/header.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">

	<!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>> <a href="StudyDestinations.php" title="Study Detinations">Study Destinations</a>><span>Study in New Zealand</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
    
<div id="content">
	
    <!-- Left Content Start From Here -->
    <div id="lt_container">
    	<h3 class="countryPage">My Options</h3>
        <!-- Content Start From Here -->
    	<div class="vertMenu">
         
         <ul>
         <li><a href="study-in-newzealand/student-visa-process.html" title="Student visa process"><span>4</span>Student visa process</a></li>
         <li><a href="study-in-newzealand/list-of-institutions.html" title="List of institutions"><span>4</span>List of institutions</a></li>
         <li><a href="study-in-newzealand/upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
         <li><a href="study-in-newzealand/whats-new.html" title="What's new"><span>4</span>What's new</a></li>
         <li><a href="study-in-newzealand/work-rights.html" title="Work rights during studies"><span>4</span>Work rights during studies</a></li>
         <li><a href="study-in-newzealand/post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights</a></li>
         <li><a href="study-in-newzealand/bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
         <li><a href="study-in-newzealand/visitor-visa.html" title="Visitor visa"><span>4</span>Visitor visa</a></li>
         </ul>
        </div>
        <div class="gap20 fl"></div>
        <div class="innerContent">
        <p>ISRA Consultants has been helping Indian students Study in New Zealand since 2009. We offer students the choice of Universities, Institutes of Technology and Polytechnics, as well as some of the top Private Training Establishments (PTE's) throughout New Zealand. ISRA Consultants have been recognized as a New Zealand Specialist Agent (NZSA) by the New Zealand Government. New Zealand Specialist Agents are required to meet strict quality criteria relating to student applications and have experience working professionally with the New Zealand international education industry.</p>

<p><strong>for more details please click the left menu options.</strong></p>

        
        </div>
        <!-- Content End Here -->
        
    </div>
    <!-- Left Content End Here -->
    
  !-- Right Content Start From Here -->
	<div id="rt_container">
         <?php require 'Views/twitter_feed.phtml'?>
            <!-- University Banner Script End Here -->
            </div>
    </div>
    <!-- Right Content End Here -->
    
</div>
</div>
<!-- Content End Here -->


<?php include_once 'Views/footer.phtml'; ?>                                                