<?php require('Views/header.phtml');?>

<!-- Content Start From Here -->
<div id="content_container">

	<!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.html" title="Home">Home</a>> <a href="study_destinations.html" title="Study Detinations">Study Destinations</a>><span>Study in Canada</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
    
<div id="content">
	
    <!-- Left Content Start From Here -->
    <div id="lt_container">
    	<h3 class="countryPage">My Options</h3>
        <!-- Content Start From Here -->
    	<div class="vertMenu">
         
         <ul>
         <li><a href="study-in-canada/student-visa-process.html" title="Student visa process"><span>4</span>Student visa process</a></li>
         <li><a href="study-in-canada/list-of-institutions.html" title="List of institutions"><span>4</span>List of institutions</a></li>
         <li><a href="study-in-canada/upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
         <li><a href="study-in-canada/whats-new.html" title="What's new"><span>4</span>What's new</a></li>
         <li><a href="study-in-canada/work-rights-for-students.html" title="Work rights during studies"><span>4</span>Work rights during studies</a></li>
         <li><a href="study-in-canada/post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights</a></li>
         <li><a href="study-in-canada/bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
         <li><a href="study-in-canada/visitor-visa.html" title="Visitor visa"><span>4</span>Visitor visa</a></li>
         </ul>
        </div>
        <div class="gap20 fl"></div>
        <div class="innerContent">
        <p>Canada is a popular choice among international students due to the country's amazing natural landscapes, award winning lifestyle and world class education standards. Since we have been recruiting students for Canada, ISRA has experienced a high visa success rate amongst our clients.</p>

<p><strong>For more details please click the left menu options.</strong></p>

        
        </div>
        <!-- Content End Here -->
        
    </div>
    <!-- Left Content End Here -->
    
    <!-- Right Content Start From Here -->
	<div id="rt_container">
        <div class="facts_container">
        	<ul id="facts">
				<li><img src="images/facts/canada/canada_1.jpg" width="300" height="105" alt="English and French are the official languages of Canada." /></li>
                <li><img src="images/facts/canada/canada_2.jpg" width="300" height="105" alt="Maple leaf is in the center of Canada's flag." /></li>
                <li><img src="images/facts/canada/canada_3.jpg" width="300" height="105" alt="Beaver is the national animal of Canada." /></li>
                <li><img src="images/facts/canada/canada_4.jpg" width="300" height="105" alt="Canada has the world's highest tertiary education enrolment." /></li>
                <li><img src="images/facts/canada/canada_5.jpg" width="300" height="105" alt="Canada has the ninth biggest economy of the world." /></li>
			</ul>        
        </div>
        <!-- University Banner Script Start From Here -->
            <div style="overflow: hidden;">
            <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
            <img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
            </div>
            <!-- University Banner Script End Here -->
            </div>
    </div>
    <!-- Right Content End Here -->
    
</div>
</div>
<!-- Content End Here -->
<?php include_once 'Views/footer.phtml'; ?>                                                