<?php require('Views/header_' . $view->headerTitle . '.phtml'); ?>

<!-- Content Start From Here -->
<div id="content_container">

    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
        <div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>> <a href="study_destinations.html" title="Study Detinations">Study Destinations</a>><span>Study in the USA</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->

    <div id="content">

        <!-- Left Content Start From Here -->
        <div id="lt_container">
            <h3 class="countryPage">My Options</h3>
            <!-- Content Start From Here -->
            <div class="vertMenu">

                <ul>
                    <li><a href="study-in-the-usa/student-visa-process.html" title="Student visa process"><span>4</span>Student visa process</a></li>
                    <li><a href="study-in-the-usa/list-of-institutions.html" title="List of institutions"><span>4</span>List of institutions</a></li>
                    <li><a href="study-in-the-usa/upcoming-interviews.html" title="Upcoming interviews"><span>4</span>Upcoming interviews</a></li>
                    <li><a href="study-in-the-usa/whats-new.html" title="What's new"><span>4</span>What's new</a></li>
                    <li><a href="study-in-the-usa/work-rights.html" title="Work rights during studies"><span>4</span>Work rights during studies</a></li>
                    <li><a href="study-in-the-usa/post-study-work-rights.html" title="Post study work rights"><span>4</span>Post study work rights </a></li>
                    <li><a href="study-in-the-usa/bringing-your-dependents.html" title="Bringing your dependents"><span>4</span>Bringing your dependents</a></li>
                    <li><a href="study-in-the-usa/visitor-visa.html" title="visitor visa"><span>4</span>Visitor visa</a></li>
                </ul>
            </div>
            <div class="gap20 fl"></div>
            <div class="innerContent">
                <p>Oceanic Consultants represents a wide range of Colleges and Universities across the USA, offering students the choice of both study program and location. Oceanic Consultants have been recognized by the American International Recruitment Council (AIRC) as an accredited agent. AIRC accreditation is a rigorous process to ensure that agents working with American institutions are ethical and qualified. This accreditation therefore provides students with the assurance that Oceanic Consultants is a trustworthy and quality organization to help you fulfill your dream of studying in the USA.</p>

                <p><strong>for more details please click the left menu options.</strong></p>


            </div>
            <!-- Content End Here -->

        </div>
        <!-- Left Content End Here -->

        <!-- Right Content Start From Here -->
        <div id="rt_container">
            <div class="facts_container">
                <ul id="facts">
                    <li><img src="images/facts/usa/usa_1.jpg" width="300" height="105" alt="Official name of Rhode Island is 'State of Rhode Island and Providence Plantations'." /></li>
                    <li><img src="images/facts/usa/usa_2.jpg" width="300" height="105" alt="It was once illegal to take a bath in the wintertime in Indiana." /></li>
                    <li><img src="images/facts/usa/usa_3.jpg" width="300" height="105" alt="The williamette River, Green River and the Kentucky River run north." /></li>
                    <li><img src="images/facts/usa/usa_4.jpg" width="300" height="105" alt="Mount Rushmore used to be called Slaughterhouse Rock." /></li>
                    <li><img src="images/facts/usa/usa_5.jpg" width="300" height="105" alt="These are 140 public airlines in Washington, including 16 state airpots." /></li>
                </ul>        
            </div>
            <!-- University Banner Script Start From Here -->
            <div style="overflow: hidden;">
            <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

                <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
                <img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
            </div>
            <!-- University Banner Script End Here -->
        </div>
    </div>
    <!-- Right Content End Here -->

</div>
</div>
<!-- Content End Here -->

<?php include_once 'Views/footer.phtml'; ?>                                                