<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>Work with us</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Work with us</h3>
                
                <div style="overflow: hidden;">
                    Whether you would like a career with ISRA, or if you are an education Institution looking to partner with us for student recruitment, the options below will provide you with the relevant information and contact details.
                    <br /><br />
                </div>
                
                <div style="overflow: hidden;">
                	<div id="box_container">
                        <div class="box1">
                            <h3>Careers with ISRA</h3>
                            <p>Want to become a key team member with one of the world leaders in overseas education? Click here for more information.</p>
                            <p><a href="Careers.php" title="Read More"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;" /></a></p>
                        </div>
                        <div class="box1 lt_mrgn">
                            <h3>Institutional Partners</h3>
                            <p>Are you an education institution looking to increase your international student numbers? Click here for more information.</p>
                            <p><a href="Partner.php" title="Read More"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;" /></a></p>
                        </div>                        
                    </div>
                </div>             
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">            
            <?php require 'Views/destinations_carousel.phtml';?>
            
            <div class="credentials">        	
                <a href="#" class="prev"></a>
                <div class="credential_scoller">            
                <div class="jCarouselLite">
                    <ul>
                        <li><img src="images/airc_logo.png" alt="American International Recruitment Council" /></li>
                        <li><img src="images/evisa_logo.png" alt="eVisa" /></li>              
                        <li><img src="images/nez_specialist_logo.png" alt="New Zealand Education Specialist Agent" /></li>                        
                        <li><img src="images/aaeri_logo.png" alt="Education In Australia" /></li>
                        <li><img src="images/aus_buss_award_logo.png" alt="Australian Business Award Winner 2010" /></li>
                        <li><img src="images/brw_award.png" alt="BRW Fast 100 Award" /></li>
                        <li><img src="images/coco_logo.png" alt="Company Owned Company Operated" /></li>
                    </ul>
                </div>
                </div>
                <a href="#" class="next"></a>
            </div>
            
                    <div style="overflow: hidden;">
        <!--<img src="images/adv_banner_2.jpg" width="301" height="88" alt="free admission in oversease, all cources consultants" style="border: none; margin-top: 15px;" />-->

        <div style="border: none; margin-top: 15px;"><iframe src="university_banners.html" width="301" height="88" frameborder="0" scrolling="no"></iframe></div>
        <img src="images/adv_banner_1.jpg" width="301" height="87" alt="" style="border: none; margin-top: 15px;" />
        </div>
        <!-- University Banner Script End Here -->

        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->

<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='Work With Us']").addClass('active');                                                   
     });
 </script>
<?php include_once 'Views/footer.phtml'; ?>                                                