<?php require('Views/header.phtml');?>
<!-- Content Start From Here -->
<div id="content_container">
	
    <!-- Liner Background Start From Here -->
    <div id="liner_bg_container">
    	<div class="liner_bg">
            <div class="breadcrumb"><a href="index.php" title="Home">Home</a>><span>Work with us</span></div>
            <div class="img"><img src="images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right" /></div>
        </div>
    </div>
    <!-- Liner Background End Here -->
	
    <div id="content">
        
        <!-- Left Content Start From Here -->
        <div id="lt_container">
            
            <!-- Content Start From Here -->
            <div class="cnt_txt">
                <h3 class="heading">Work with us</h3>
                
                <div style="overflow: hidden;">
                    Whether you would like a career with ISRA, or if you are an education Institution looking to partner with us for student recruitment, the options below will provide you with the relevant information and contact details.
                    <br /><br />
                </div>
                
                <div style="overflow: hidden;">
                	<div id="box_container">
                        <div class="box1">
                            <h3>Careers with ISRA</h3>
                            <p>Want to become a key team member with one of the world leaders in overseas education? Click here for more information.</p>
                            <p><a href="Careers.php" title="Read More"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;" /></a></p>
                        </div>
                        <div class="box1 lt_mrgn">
                            <h3>Institutional Partners</h3>
                            <p>Are you an education institution looking to increase your international student numbers? Click here for more information.</p>
                            <p><a href="Partner.php" title="Read More"><img src="images/readmore.png" width="65" height="24" alt="" style="border-width: 0px;" /></a></p>
                        </div>                        
                    </div>
                </div>             
            </div>
            <!-- Content End Here -->
            
        </div>
        <!-- Left Content End Here -->
        
        <!-- Right Content Start From Here -->
        <div id="rt_container">            
            <?php require 'Views/destinations_carousel.phtml';?>
            <?php require 'Views/twitter_feed.phtml'?>    

        </div>
        <!-- Right Content End Here -->
        
    </div>
    
</div>
<!-- Content End Here -->

<script type="text/javascript">
     $(document).ready(function() {
       $('#smoothmenu1').find(".active").removeClass('active');
       $("a[title='Work With Us']").addClass('active');                                                   
     });
 </script>
<?php include_once 'Views/footer.phtml'; ?>                                                