    <!-- Banner Start From Here -->
    <div id="banner">
    	<div class="model"><img src="../images/study_in_abroad_(small).png" width="128" height="203" align="right" alt="Study in abroad"></div>
		
        <!-- Banner Backgrounds Start From Here -->        
        <div class="banner_countries">
        	<img src="../images/header_contries_bg_inner.png" alt="" width="761" height="201" border="0" usemap="#studies_locations" style="margin-left: 30px;">
            <map name="studies_locations" id="studies_locations">
            <area shape="poly" coords="648,90,663,72,690,65,719,64,750,74,763,91,752,111,710,121,662,114" href="Register.php" target="_self" title="Register Now">
<area shape="poly" coords="500,199,503,172,522,162,537,162,550,153,565,142,580,118,577,153,575,170,573,183,576,199" href="StudyInNewZealand.php" title="Study in New Zealand">
            <area shape="rect" coords="2,75,51,129" href="StudyInCanada.php" title="Study in Canada" alt="Canada">
            <area shape="poly" coords="103,88,103,200,181,200" href="StudyInTheUSA.php" title="Study in the USA" alt="USA">
            <area shape="rect" coords="227,6,263,101" href="StudyInTheUk.php" title="Study in the UK" alt="UK">
            <area shape="poly" coords="311,130,347,157,367,151,397,155,384,166,421,164,419,198,260,198,251,176,265,156,295,138" href="StudyInAustralia.php" title="Study in Australia" alt="Australia">
            </map>
	  	</div>

        <div class="banner_slogan_container">
            <div class="banner_slogan" style="display: block; position: absolute">
            <div id="testimonials2">
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head-common">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body-common">
                            <p>that we have placed more than 10,000 students at various institutions overseas?</p>
                        </div>
                    </div>                              
                </blockquote>
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head-common">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body-common">
                            <p>that we have one of the largest company owned offices in India?</p>
                        </div>
                    </div>                              
                </blockquote>
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head-common">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body-common">
                            <p>that we take care of everything from admission to visa to air-ticketing?</p>
                        </div>
                    </div>                              
                </blockquote>
                <blockquote >
                    <div id="header-carousel">
                        <div id="header-carousel-head-common">
                            <p>Did you know</p>
                        </div>
                        <div id="header-carousel-body-common">
                            <p>that we have one of the highest visa success rates in the industry?</p>
                        </div>
                    </div>                              
                </blockquote> 
            </div>
            </div>
        </div>
        <!-- Banner Background End Here -->
        
        
    </div>
    <!-- Banner End Here -->