<!-- Footer Start From Here -->
<div id="footer">
	<div id="footer_container">
    
    	<!-- Footer Left Start From Here -->
    	<div class="lt">
        	<div class="lnk_container">
            <ul style="margin-top: 10px;">
            <li><a href="#" title="Sitemap">Sitemap</a></li>
            <li><a href="index.php" title="Home">Home</a></li>
            <li><a href="AboutUs.php" title="About Us">About Us</a></li>
            <li><a href="Services.php" title="Services">Services</a></li>
            <li><a href="Events.php" title="Events">Events</a></li>
            <li><a href="Contact.php" title="Contact Us">Contact Us</a></li>
            </ul>
            </div>
            
            <div class="lnk_container" style="margin: 0px 20px 0px -20px;">
            <h3><a href="StudyInTheUk.php" title="Study Destinations">Study Destinations</a></h3>
            <ul>
            <li><a href="StudyInAustralia.php" title="Study in Australia"><img src="images/aus_flag.jpg" width="18" height="11" alt="Australia" border="0">&nbsp;&nbsp;Study in Australia</a></li>
            <li><a href="StudyInCanada.php" title="Study in Canada"><img src="images/canada_flag.jpg" width="18" height="11" alt="Canada" border="0">&nbsp;&nbsp;Study in Canada</a></li>
            <li><a href="StudyInNewZealand.php" title="Study in New Zealand"><img src="images/new_zeland_flag.jpg" width="18" height="11" alt="New Zealand" border="0">&nbsp;&nbsp;Study in New Zealand</a></li>
            <li><a href="StudyInTheUk.php" title="Study in the UK"><img src="images/uk_flag.jpg" width="18" height="11" alt="United Kindom" border="0">&nbsp;&nbsp;Study in the UK</a></li>
            <li><a href="StudyInTheUSA.php" title="Study in the USA"><img src="images/us_flag.jpg" width="18" height="11" alt="USA" border="0">&nbsp;&nbsp;Study in the USA</a></li>
            </ul>
            </div>
            
            <div class="lnk_container">
            <h3><a href="NewsRoom.php" title="Newsroom">Newsroom</a></h3>           
            </div>
            
            <div class="lnk_container">
            <h3><a href="WorkWithUs.php" title="Work with us">Work with us</a></h3>
            <ul>
            <li><a href="Careers.php" title="Career with ISRA">- Career with ISRA</a></li>
            <li><a href="Partner.php" title="Partner with ISRA">- Partner with ISRA</a></li>
            </ul>
            </div>            
        </div>
        <!-- Footer Left End Here -->
        
        <!-- Footer Right Start From Here -->
        <div class="rt">
            <div class="lnk_container">            
            <h3>Follow us on:</h3>
            <img src="images/social_websites_icons.jpg" alt="" width="28" height="28" border="0" usemap="#Map">
            <map name="Map" id="Map">
                <area shape="rect" coords="2,1,28,26" href="#" target="_blank" title="Find us on Youtube" alt="Youtube">
            </map>

           
            </div>
        </div>
        <!-- Footer Right End Here -->
    </div>    
    <div id="footer_btm">
    	<div id="footer_btm_container">
        	<p align="right">© 2013, International Student Recruitment Agency. all rights reserved. | <a href="PrivacyPolicy.php" title="Privacy Policy">privacy policy</a></p>
        </div>
    </div>
</div>
<!-- Footer End Here -->
</body></html>