<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0044)ISRAindex.html -->
<html xmlns="http://www.w3.org/1999/xhtml" class="cufon-active cufon-ready"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

            <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8">
                <meta name="Keywords" content="Study in canada, Study in united kingdom, Study in new zealand, Study in australia, visa to uk, Study in united states">
                    <meta name="Description" content="ISRA consultants provide best consultant services for overseas education. It helps students to get admission in  universities in Australia, Canada, New Zealand, UK, USA.">
                        <title>Study in UK | Study in New Zealand | Study in The USA | Study in Canada | Study in Australia | Overseas Education | Study in Overseas | Study Consultants</title>
                        
                        <link href="../css/<?php echo $view->headerTitle?>.css" type="text/css" rel="stylesheet">
                 
                       
<link rel="stylesheet" type="text/css" href="../css/ddsmoothmenu.css" />
<link rel="stylesheet" type="text/css" href="../css/jquery-ui.css" />

<script type="text/javascript" src="../js/jquery.min.js"></script>
<script type="text/javascript" src="../js/ddsmoothmenu.js"></script>

<script type="text/javascript" src="../js/jquery-latest.pack.js"></script>
<script type="text/javascript" src="../js/jcarousellite_1.0.1.js"></script>
<script type="text/javascript" src="../js/jquery.innerfade.js"></script>

<script type="text/javascript" src="../js/common.js"></script>

<script type="text/javascript" src="../js/cufon-yui.js"></script>
<script type="text/javascript" src="../js/Segoe_Script_400-Segoe_Script_700.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.banner_slogan h3', { fontFamily: 'Segoe Script' });
</script>

<script type="text/javascript" src="../js/jquery-ui.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
	$("#accordion").accordion({ autoHeight: false });	
});
</script>





                                    <!-- include Cycle plugin -->
                                    <script type="text/javascript" src="https://filemasbayu.googlecode.com/files/jquery.cycle.all.latest.js"></script>

                                    <script type="text/javascript">
                                        $(document).ready(function() {
                                            $('#testimonials1')
                                                    .after('<div id="nav2">')
                                                    .cycle({
                                                fx: 'fade', // choose your transition type, ex: fade, scrollUp, scrollRight, shuffle
                                                //pager:  '#nav2'              
                                            });
                                            $('#testimonials1').css('height', '40px');


                                            $('#testimonials2')
                                                    .after('<div id="nav2">')
                                                    .cycle({
                                                fx: 'fade', // choose your transition type, ex: fade, scrollUp, scrollRight, shuffle
                                                //pager:  '#nav2'

                                            });
                                        });
                                    </script>   
                                    <script type="text/javascript">
                                        $(function() {
                                            $(".credential_scoller").jCarouselLite({
                                                btnNext: ".next",
                                                btnPrev: ".prev"
                                            });
                                        });
                                    </script>
                                  </head>
                                    <body>

                                        <!-- Header Start From Here -->
                                        <div id="header">

                                            <?php require('menu.phtml') ?>                                            
                                            <?php require('banner_'.$view->bannerTitle.'.phtml');?>  
                                            <?php if($view->bannerTitle == 'home'){
                                                require('testimonials.phtml') ?>
                                            <!-- Banner Bottom Start From Here -->
                                            <div id="banner_bottom">&nbsp;</div>
                                            <!-- Banner Bottom End Here -->

                                            <!-- Liner Background Start From Here -->
                                            <div id="liner_bg">
                                                <div class="img"><img src="../images/free_img.jpg" width="301" height="22" alt="all are services are FREE of charge" align="right"></div>
                                            </div>
                                            <!-- Liner Background End Here -->
                                           
                                            <?php } ?>  

                                        </div>
                                        <!-- Header End Here -->