  <!-- Top Header Start From Here -->
    <div id="top_header"></div>    
    <div id="logo_container">
	    <div id="logo"><a href="index.php" title="ISRA Consultants"><img src="../images/logo.png" width="243" height="124" alt="ISRA Consultants" border="0"></a></div>
        <!-- Login Box Start From Here -->
        <div id="login_box_container">
        	<a href="Register.php" class="reg_lnk" title="Register Now">Register Now</a>
        	<iframe src="./ISRAWeb_files/clientlogin.htm" width="100%" height="40" frameborder="0" scrolling="no"></iframe>
        </div>
        <!-- Login Box End Here -->
        
    </div>
    <!-- Top Header End Here -->
   
    <!-- Navigation Start From Here -->
    <div id="menu">
    	<div id="menu_container">
	        <div class="lt">&nbsp;</div>
            <div class="rt">
				<div id="smoothmenu1" class="ddsmoothmenu">
                <ul>
                    <li><a href="index.php" title="Home" class="active">Home</a></li>
                    <li><a href="AboutUs.php" title="About Us">About Us</a></li>
                    <li><a href="Services.php" title="Services">Services</a></li>
                    <li><a href="Events.php" title="Events">Events</a></li>
                    <li><a href="Contact.php" title="Contact Us">Contact Us</a></li>
                    <li><a href="NewsRoom.php" title="Newsroom">Newsroom</a>
                        <!--<ul>
                            <li><a href="news_room.html" title="What's new?">What's new?</a></li>
                            <li><a href="in_press.html" title="ISRA in press">ISRA in press</a></li>
                        </ul>-->
                    </li>
                    <li style="z-index: 100;"><a href="WorkWithUS.php" title="Work With Us" style="padding-right: 25px;">Work With Us<img src="../images/down.png" class="downarrowclass" style="border:0;"></a>
                        <ul style="display: none; top: 38px; box-shadow: rgb(170, 170, 170) 5px 5px 5px; -webkit-box-shadow: rgb(170, 170, 170) 5px 5px 5px; visibility: visible;">
                            <li><a href="Careers.php" title="Careers with ISRA">Careers with ISRA</a></li>
                            <li><a href="Partner.php" title="Partner with ISRA">Partner with ISRA</a></li>
                        </ul>
                    </li>
                </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Navigation End Here -->